begin;
do $test$
declare actor uuid; org uuid; account uuid; category uuid; entry uuid; cmd uuid; body jsonb; baseline jsonb; before_value numeric;
begin
 select user_id,organization_id into strict actor,org from public.user_roles where role_id='administrator' limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 account=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"account","name":"Teste exclusão rollback","type":"bancaria","opening_balance":"0.00"}');
 category=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Teste exclusão rollback","type":"despesa"}');
 baseline=public.get_financial_summary(org,1);
 body=jsonb_build_object('operation','save','type','despesa','description','Teste exclusão rollback','amount','100.00','status','paid','account_id',account,'category_id',category,'competence_date','2026-01-01','due_date','2026-01-01','paid_date',((now() at time zone 'America/Sao_Paulo')::date)::text);
 entry=public.save_financial_entry(org,gen_random_uuid(),body);
 cmd=gen_random_uuid();
 perform public.revise_financial_entry(org,cmd,jsonb_build_object('operation','amend','id',entry,'version',1,'description','Teste exclusão corrigido','notes','Corrigido','amount','1.00'));
 if (select descricao from public.transacoes where id=entry)<>'Teste exclusão corrigido' or (select valor from public.transacoes where id=entry)<>100 then raise exception 'Metadata amendment failed or changed paid value'; end if;
 begin perform public.revise_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','remove','id',entry,'version',1)); raise exception 'Stale removal accepted'; exception when serialization_failure then null; end;
 cmd=gen_random_uuid();body=jsonb_build_object('operation','remove','id',entry,'version',2);
 perform public.revise_financial_entry(org,cmd,body);perform public.revise_financial_entry(org,cmd,body);
 if not exists(select 1 from public.transacoes where id=entry and deletada_em is not null and deleted_by=actor) then raise exception 'Historical row or actor lost'; end if;
 if (select count(*) from public.financial_payments where entry_id=entry)<>1 then raise exception 'Payment history removed'; end if;
 if (public.get_financial_entries(org,'{"q":"Teste exclusão corrigido"}',1)->>'total')::integer<>0 then raise exception 'Deleted entry still listed'; end if;
 if public.get_financial_summary(org,1)->>'balance'<>baseline->>'balance' or public.get_financial_summary(org,1)->>'paid'<>baseline->>'paid' then raise exception 'Deleted cash still in totals'; end if;
 if (select count(*) from public.audit_logs where entity_id=entry::text)<>3 then raise exception 'Audit retry duplicated'; end if;
 begin perform public.revise_financial_entry(gen_random_uuid(),gen_random_uuid(),body); raise exception 'Foreign organization writes'; exception when insufficient_privilege then null; end;
 entry=public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','save','type','despesa','description','Teste em aberto rollback','amount','10.00','status','pending','account_id',account,'category_id',category,'competence_date','2026-01-01','due_date','2026-01-01'));
 if (public.get_financial_entries(org,'{"q":"Teste em aberto rollback","type":"despesa","status":"open"}',1)->>'total')::integer<>1 then raise exception 'Open payables filter failed'; end if;
 if (public.get_financial_entries(org,'{"q":"Teste em aberto rollback","type":"receita","status":"open"}',1)->>'total')::integer<>0 then raise exception 'Receivables includes payables'; end if;
 execute 'reset role';
 update public.user_roles set role_id='viewer' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 begin perform public.revise_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','remove','id',entry,'version',1)); raise exception 'Viewer removes'; exception when insufficient_privilege then null; end;
 execute 'reset role';execute 'set local role anon';
 begin perform public.revise_financial_entry(org,gen_random_uuid(),body); raise exception 'Anonymous writes'; exception when insufficient_privilege then null; end;
 execute 'reset role';set constraints all immediate;
end $test$;
rollback;
select 'PASS: edit metadata, retained paid amount, soft deletion, balance and monthly totals, preserved journal and audit, idempotency, stale version, open payables/receivables and authorization; rolled back' as result;
