begin;
do $test$ declare actor uuid; org uuid; account uuid; cat uuid; child uuid; center uuid; key uuid=gen_random_uuid(); n integer; body jsonb; begin
 select id into actor from auth.users where email='agenciaatomo10@gmail.com';
 select organization_id into org from public.organization_members where user_id=actor;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 body=jsonb_build_object('kind','account','name','Teste temporário','type','bancaria','opening_balance','123.45');
 account=public.save_financial_catalog(org,key,body);
 if public.save_financial_catalog(org,key,body)<>account then raise exception 'idempotency failed'; end if;
 begin perform public.save_financial_catalog(org,key,body||'{"name":"different"}'); raise exception 'payload mismatch accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"account","name":"invalid","type":"bancaria","opening_balance":"0.001"}'); raise exception 'fraction cents accepted'; exception when invalid_parameter_value then null; end;
 perform public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('kind','account','id',account,'name','Teste temporário editado','type','digital'));
 if not exists(select 1 from public.contas_bancarias where id=account and nome='Teste temporário editado' and tipo='digital' and ativa) then raise exception 'account edit failed'; end if;
 if (select saldo_inicial from public.contas_bancarias where id=account)<>123.45 then raise exception 'money failed'; end if;
 if jsonb_typeof(public.get_financial_catalog(org,'account','Teste',1)->'items'->0->'opening_balance')<>'string' then raise exception 'decimal transport failed'; end if;
 cat=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Pai temporário","type":"despesa"}');
 child=public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('kind','category','name','Filho temporário','type','despesa','parent_id',cat));
 begin perform public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('kind','category','id',cat,'name','Pai temporário','type','despesa','parent_id',child)); raise exception 'cycle accepted'; exception when invalid_parameter_value then null; end;
 center=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"cost_center","name":"Centro temporário"}');
 perform public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('kind','cost_center','operation','archive','id',center));
 if (select active from public.cost_centers where id=center) then raise exception 'archive failed'; end if;
 perform public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('kind','account','operation','archive','id',account));
 if exists(select 1 from public.contas_bancarias where id=account) then raise exception 'account delete failed'; end if;
 if (public.get_financial_catalog(org,'account','%',1)->>'total')::int<>0 then raise exception 'search wildcard not escaped'; end if;
 select count(*) into n from public.audit_logs where entity_id=account::text and domain='financial'; if n<>2 then raise exception 'audit or retry duplicated'; end if;
 execute 'reset role';
 update public.user_roles set role_id='viewer' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 begin perform public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"cost_center","name":"denied"}'); raise exception 'viewer writes'; exception when insufficient_privilege then null; end;
 execute 'reset role';
end $test$;
rollback; select 'PASS: catalogs, account edit/delete, exact money, idempotency, mismatched retry, hierarchy/cycle, archive, escaped search, audit, viewer denied; rolled back' as result;
