begin;
do $test$
declare actor uuid; org uuid; account uuid; category uuid; center uuid; entry uuid; paid_entry uuid;
 key uuid=gen_random_uuid(); body jsonb; changed jsonb; count_before bigint; audits bigint; original_count bigint;
begin
 select user_id,organization_id into strict actor,org from public.user_roles where role_id='administrator' limit 1;
 select count(*) into original_count from public.transacoes where source_type='legacy';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 account=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"account","name":"Teste rollback lançamentos","type":"bancaria","opening_balance":"0.00"}');
 category=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Teste rollback lançamentos","type":"despesa"}');
 center=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"cost_center","name":"Teste rollback lançamentos"}');
 body=jsonb_build_object('operation','save','type','despesa','description','Teste lançamento 100%','amount','1234.56','status','pending','account_id',account,'category_id',category,'cost_center_id',center,'competence_date','2026-01-01','due_date','2026-01-05','paid_date','','notes','Teste revertido');
 entry=public.save_financial_entry(org,key,body);
 if public.save_financial_entry(org,key,body)<>entry then raise exception 'Retry not idempotent'; end if;
 if (select valor from public.transacoes where id=entry)<>1234.56 then raise exception 'Money not exact'; end if;
 if (select created_by from public.transacoes where id=entry)<>actor then raise exception 'Creator not Auth'; end if;
 if (public.get_financial_entries(org,'{"q":"100%","status":"overdue"}',1)->>'total')::int<>1 then raise exception 'Overdue/literal search failed'; end if;
 if jsonb_typeof(public.get_financial_entries(org,'{"q":"100%"}',1)->'items'->0->'amount')<>'string' then raise exception 'Decimal transport failed'; end if;
 if (public.get_financial_entries(org,'{"q":"100%","from":"2026-02-01"}',1)->>'total')::int<>0 then raise exception 'Date filter failed'; end if;
 if (public.get_financial_entries(org,'{"q":"100%"}',2)->'items')<>'[]'::jsonb then raise exception 'Pagination failed'; end if;
 select count(*) into audits from public.audit_logs where entity_id=entry::text;
 if audits<>1 then raise exception 'Audit duplicated on retry'; end if;
 begin perform public.save_financial_entry(org,key,body||'{"amount":"12.00"}'); raise exception 'Mismatched retry accepted'; exception when invalid_parameter_value then null; end;
 foreach changed in array array['{"amount":"0.001"}'::jsonb,'{"amount":"0"}','{"amount":"-1"}','{"amount":"1e3"}','{"amount":"NaN"}','{"paid_date":"2026-01-01"}','{"type":"receita"}','{"competence_date":""}','{"account_id":null}','{"category_id":null}','{"status":null}'] loop
  begin perform public.save_financial_entry(org,gen_random_uuid(),body||changed); raise exception 'Invalid data accepted: %',changed; exception when invalid_parameter_value then null; end;
 end loop;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body||'{"due_date":"2026-02-30"}'); raise exception 'Invalid calendar date accepted'; exception when datetime_field_overflow then null; end;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('status','paid','paid_date',((now() at time zone 'America/Sao_Paulo')::date+1)::text)); raise exception 'Future payment accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('cost_center_id',gen_random_uuid())); raise exception 'Unknown relation accepted'; exception when invalid_parameter_value then null; end;
 begin perform public.save_financial_entry(gen_random_uuid(),gen_random_uuid(),body); raise exception 'Other organization accepted'; exception when insufficient_privilege then null; end;
 changed=body||jsonb_build_object('id',entry,'version',1,'amount','999.99');
 perform public.save_financial_entry(org,gen_random_uuid(),changed);
 begin perform public.save_financial_entry(org,gen_random_uuid(),changed); raise exception 'Lost update accepted'; exception when serialization_failure then null; end;
 key=gen_random_uuid();changed=jsonb_build_object('operation','settle','id',entry,'version',2,'paid_date','2026-01-07');
 perform public.save_financial_entry(org,key,changed);
 perform public.save_financial_entry(org,key,changed);
 if (select version from public.transacoes where id=entry)<>3 or (select paid_date from public.transacoes where id=entry)<>date '2026-01-07' then raise exception 'Settlement retry duplicated'; end if;
 begin perform public.save_financial_entry(org,gen_random_uuid(),changed); raise exception 'Paid entry mutable'; exception when invalid_parameter_value then null; end;
 begin perform public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','cancel','id',entry,'version',3,'reason','Teste')); raise exception 'Paid entry cancelled without reversal'; exception when invalid_parameter_value then null; end;
 paid_entry=public.save_financial_entry(org,gen_random_uuid(),body||'{"status":"paid","paid_date":"2026-01-07"}');
 if (select status from public.transacoes where id=paid_entry)<>'paid' then raise exception 'Initial paid entry failed'; end if;
 entry=public.save_financial_entry(org,gen_random_uuid(),body);
 perform public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','cancel','id',entry,'version',1,'reason','Duplicado por engano'));
 if (select cancellation_reason from public.transacoes where id=entry)<>'Duplicado por engano' or (select status from public.transacoes where id=entry)<>'cancelled' then raise exception 'Cancellation failed'; end if;
 begin update public.transacoes set valor=1 where id=entry; raise exception 'Direct update allowed'; exception when insufficient_privilege then null; end;
 begin delete from public.transacoes where id=entry; raise exception 'Direct delete allowed'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 -- An injected audit failure must roll back the financial record and command together.
 select count(*) into count_before from public.transacoes;
 execute 'create function private.test_reject_entry_audit() returns trigger language plpgsql as $fn$ begin if new.entity=''transacoes'' then raise exception ''Injected audit failure'' using errcode=''P0002''; end if; return new; end $fn$';
 execute 'create trigger test_reject_entry_audit before insert on public.audit_logs for each row execute function private.test_reject_entry_audit()';
 execute 'set local role authenticated';
 key=gen_random_uuid();
 begin perform public.save_financial_entry(org,key,body); raise exception 'Injected failure ignored'; exception when no_data_found then null; end;
 execute 'reset role';
 if (select count(*) from public.transacoes)<>count_before or exists(select 1 from private.financial_entry_commands where request_id=key) then raise exception 'Atomic rollback failed'; end if;
 execute 'drop trigger test_reject_entry_audit on public.audit_logs';execute 'drop function private.test_reject_entry_audit()';
 update public.user_roles set role_id='viewer' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 perform public.get_financial_entries(org,'{}',1);
 begin perform public.save_financial_entry(org,gen_random_uuid(),body); raise exception 'Viewer writes'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update public.user_roles set role_id='operational' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 begin perform public.get_financial_entries(org,'{}',1); raise exception 'Operational reads financial'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update public.organization_members set active=false where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 if exists(select 1 from public.transacoes where empresa_id=org) then raise exception 'Revoked member reads directly'; end if;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body); raise exception 'Revoked member writes'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 execute 'set local role anon';
 begin perform public.get_financial_entries(org,'{}',1); raise exception 'Anonymous calls RPC'; exception when insufficient_privilege then null; end;
 begin perform 1 from public.transacoes; raise exception 'Anonymous reads table'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 if (select count(*) from public.transacoes where source_type='legacy')<>original_count then raise exception 'Legacy modified'; end if;
end $test$;
rollback;
select 'PASS: create/edit/settle/cancel, decimal validation, date filters, pagination, idempotency, optimistic locking, audit rollback, immutable paid history, permissions and legacy preservation; all changes rolled back' as result;
