begin;
do $test$
declare actor uuid; org uuid; account uuid; category uuid; income_category uuid; entry uuid; baseline jsonb; result jsonb; body jsonb; today date=(now() at time zone 'America/Sao_Paulo')::date;
begin
 select user_id,organization_id into strict actor,org from public.user_roles where role_id='administrator' limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 baseline=public.get_financial_summary(org,1);
 account=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"account","name":"AAA Resumo rollback","type":"bancaria","opening_balance":"100.00"}');
 category=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Resumo rollback saída","type":"despesa"}');
 income_category=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Resumo rollback entrada","type":"receita"}');
 body=jsonb_build_object('operation','save','type','receita','description','Resumo rollback entrada','amount','100.00','status','paid','account_id',account,'category_id',income_category,'competence_date',today::text,'due_date',today::text,'paid_date',today::text);
 perform public.save_financial_entry(org,gen_random_uuid(),body);
 entry=public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('type','despesa','category_id',category,'amount','60.00','status','pending','paid_date',''));
 perform public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','settle','id',entry,'version',1,'settlement_amount','20.00','paid_date',today::text));
 perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('type','despesa','category_id',category,'amount','30.00','paid_date',(date_trunc('month',today)::date-1)::text));
 perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('amount','50.00','status','pending','paid_date','','due_date',(today+40)::text));
 entry=public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('type','despesa','category_id',category,'amount','30.00','status','pending','paid_date',''));
 perform public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','cancel','id',entry,'version',1,'reason','Cancelamento de teste'));
 perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('type','despesa','category_id',category,'amount','90.00','status','pending','paid_date','','installments',3));
 result=public.get_financial_summary(org,1);
 if (result->>'balance')::numeric-(baseline->>'balance')::numeric<>150 then raise exception 'Balance counts obligations or double counts payments'; end if;
 if (result->>'received')::numeric-(baseline->>'received')::numeric<>100 or (result->>'paid')::numeric-(baseline->>'paid')::numeric<>20 then raise exception 'Monthly cash / partial / previous-month boundary failed'; end if;
 if (result->>'receivable')::numeric-(baseline->>'receivable')::numeric<>50 or (result->>'payable')::numeric-(baseline->>'payable')::numeric<>130 then raise exception 'Outstanding includes cancelled or duplicate plan'; end if;
 if jsonb_typeof(result->'balance')<>'string' or jsonb_typeof(result->'paid')<>'string' then raise exception 'Decimal transport failed'; end if;
 perform public.save_financial_catalog(org,gen_random_uuid(),jsonb_build_object('operation','archive','kind','account','id',account));
 if public.get_financial_summary(org,1)->>'balance'<>result->>'balance' then raise exception 'Archiving account erased cash'; end if;
 if public.get_financial_summary(org,100000)->'accounts'<>'[]'::jsonb then raise exception 'Account pagination failed'; end if;
 execute 'reset role';
 insert into public.transacoes(empresa_id,conta_id,tipo,descricao,valor,data_lancamento,status) values(org,account,'receita','Resumo legado rollback',7,today,'confirmada');
 execute 'set local role authenticated';
 result=public.get_financial_summary(org,1);
 if (result->>'balance')::numeric-(baseline->>'balance')::numeric<>157 or (result->>'received')::numeric-(baseline->>'received')::numeric<>100 then raise exception 'Legacy was lost or assigned fictitious cash date'; end if;
 execute 'reset role';
 update public.user_roles set role_id='viewer' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';perform public.get_financial_summary(org,1);
 begin perform public.get_financial_summary(gen_random_uuid(),1); raise exception 'Foreign organization read'; exception when insufficient_privilege then null; end;
 execute 'reset role';update public.organization_members set active=false where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 begin perform public.get_financial_summary(org,1); raise exception 'Revoked member read'; exception when insufficient_privilege then null; end;
 execute 'reset role';execute 'set local role anon';
 begin perform public.get_financial_summary(org,1); raise exception 'Anonymous read'; exception when insufficient_privilege then null; end;
 execute 'reset role';set constraints all immediate;
end $test$;
rollback;
select 'PASS: balances, monthly cash, partial payments, prior month, outstanding, cancelled exclusions, no duplicate installment totals, legacy, archived accounts, pagination, decimal transport and RLS; rollback' as result;
