begin;
do $test$
declare actor uuid; org uuid; account uuid; category uuid; entry uuid; plan uuid; cmd uuid=gen_random_uuid(); body jsonb; payment jsonb; changed jsonb;
 n bigint; m bigint; a bigint; plan_count bigint; first_amount numeric;
begin
 select user_id,organization_id into strict actor,org from public.user_roles where role_id='administrator' limit 1;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
 execute 'set local role authenticated';
 account=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"account","name":"Teste parcelas rollback","type":"bancaria","opening_balance":"0.00"}');
 category=public.save_financial_catalog(org,gen_random_uuid(),'{"kind":"category","name":"Teste parcelas rollback","type":"despesa"}');
 body=jsonb_build_object('operation','save','type','despesa','description','Teste parcelas 100% rollback','amount','100.00','status','pending','account_id',account,'category_id',category,'competence_date','2026-01-01','due_date','2026-01-31','installments',3);
 entry=public.save_financial_entry(org,cmd,body);
 if public.save_financial_entry(org,cmd,body)<>entry then raise exception 'Plan retry failed'; end if;
 select installment_group,valor into plan,first_amount from public.transacoes where id=entry;
 if first_amount<>33.34 then raise exception 'First cent allocation failed'; end if;
 if (select sum(valor) from public.transacoes where installment_group=plan)<>100 or (select count(*) from public.transacoes where installment_group=plan)<>3 then raise exception 'Plan total failed'; end if;
 if (select due_date from public.transacoes where installment_group=plan and installment_number=2)<>date '2026-02-28' or (select due_date from public.transacoes where installment_group=plan and installment_number=3)<>date '2026-03-31' then raise exception 'Month-end anchor failed'; end if;
 execute 'set constraints all immediate';execute 'set constraints all deferred';
 begin perform public.save_financial_entry(org,cmd,body||'{"amount":"200.00"}'); raise exception 'Different retry accepted'; exception when invalid_parameter_value then null; end;
 foreach changed in array array['{"installments":0}'::jsonb,'{"installments":121}','{"installments":1.5}','{"installments":3,"amount":"0.02"}','{"installments":3,"status":"paid","paid_date":"2026-01-01"}','{"due_date":"2199-12-31","installments":2}'] loop
  begin perform public.save_financial_entry(org,gen_random_uuid(),body||changed); raise exception 'Invalid plan accepted: %',changed; exception when invalid_parameter_value then null; end;
 end loop;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('id',entry,'version',1,'installments',1,'amount','40.00')); raise exception 'Installment amount edited'; exception when invalid_parameter_value then null; end;
 cmd=gen_random_uuid();payment=jsonb_build_object('operation','settle','id',entry,'version',1,'paid_date','2026-01-15','settlement_amount','10.00','payment_notes','Primeira parte');
 perform public.save_financial_entry(org,cmd,payment);
 perform public.save_financial_entry(org,cmd,payment);
 if (select status from public.transacoes where id=entry)<>'partially_paid' or (select paid_amount from public.transacoes where id=entry)<>10 or (select paid_date from public.transacoes where id=entry) is not null then raise exception 'Partial state failed'; end if;
 if (select count(*) from public.financial_payments where entry_id=entry)<>1 then raise exception 'Payment retry duplicated'; end if;
 if public.get_financial_entries(org,'{"q":"Teste parcelas 100% rollback","status":"partially_paid"}',1)->'items'->0->>'outstanding_amount'<>'23.34' then raise exception 'Outstanding total failed'; end if;
 if (public.get_financial_entries(org,'{"q":"Teste parcelas 100% rollback","basis":"paid","from":"2026-01-15","to":"2026-01-15"}',1)->>'total')::integer<>1 then raise exception 'Partial cash date filter failed'; end if;
 if jsonb_typeof(public.get_financial_payments(org,entry,1)->'items'->0->'amount')<>'string' then raise exception 'Payment decimal transport failed'; end if;
 begin perform public.save_financial_entry(org,gen_random_uuid(),payment); raise exception 'Stale payment version accepted'; exception when serialization_failure then null; end;
 foreach changed in array array['{"settlement_amount":"23.35"}'::jsonb,'{"settlement_amount":"0"}','{"settlement_amount":"0.001"}','{"settlement_amount":"-1"}'] loop
  begin perform public.save_financial_entry(org,gen_random_uuid(),payment||'{"version":2}'||changed); raise exception 'Invalid partial amount accepted'; exception when invalid_parameter_value then null; end;
 end loop;
 begin perform public.save_financial_entry(org,gen_random_uuid(),jsonb_build_object('operation','cancel','id',entry,'version',2,'reason','Teste')); raise exception 'Partial cancelled'; exception when invalid_parameter_value then null; end;
 begin perform public.save_financial_entry(org,gen_random_uuid(),body||jsonb_build_object('id',entry,'version',2,'installments',1,'amount','33.34')); raise exception 'Partial edited'; exception when invalid_parameter_value then null; end;
 execute 'set constraints all immediate';execute 'set constraints all deferred';
 execute 'reset role';
 begin
  update public.transacoes set paid_amount=11 where id=entry;
  execute 'set constraints all immediate';
  raise exception 'Journal invariant not enforced';
 exception when check_violation then null; end;
 execute 'set constraints all deferred';
 execute 'set local role authenticated';
 perform public.save_financial_entry(org,gen_random_uuid(),payment||'{"version":2,"settlement_amount":"23.34","paid_date":"2026-01-10"}');
 if (select status from public.transacoes where id=entry)<>'paid' or (select paid_amount from public.transacoes where id=entry)<>33.34 or (select paid_date from public.transacoes where id=entry)<>date '2026-01-15' then raise exception 'Full settlement after partial failed'; end if;
 if (select sum(amount) from public.financial_payments where entry_id=entry)<>33.34 or (select valor from public.transacoes where id=entry)<>33.34 then raise exception 'Original amount changed'; end if;
 execute 'set constraints all immediate';execute 'set constraints all deferred';
 execute 'reset role';
 -- Fail on the third installment, after preceding inserts and audit events.
 select count(*) into n from public.transacoes;select count(*) into a from public.audit_logs;select count(*) into plan_count from public.financial_installment_plans;
 execute 'create function private.test_fail_installment() returns trigger language plpgsql as $fn$ begin if new.installment_number=3 then raise exception ''Injected failure'' using errcode=''P0002''; end if; return new; end $fn$';
 execute 'create trigger test_fail_installment before insert on public.transacoes for each row execute function private.test_fail_installment()';
 cmd=gen_random_uuid();execute 'set local role authenticated';
 begin perform public.save_financial_entry(org,cmd,body); raise exception 'Injected plan failure ignored'; exception when no_data_found then null; end;
 execute 'reset role';
 if (select count(*) from public.transacoes)<>n or (select count(*) from public.audit_logs)<>a or (select count(*) from public.financial_installment_plans)<>plan_count or exists(select 1 from private.financial_entry_commands where request_id=cmd) then raise exception 'Partial plan persisted'; end if;
 execute 'drop trigger test_fail_installment on public.transacoes';execute 'drop function private.test_fail_installment()';
 select id into entry from public.transacoes where installment_group=plan and installment_number=2;
 select count(*) into m from public.financial_payments;select count(*) into a from public.audit_logs;
 execute 'create function private.test_fail_payment_audit() returns trigger language plpgsql as $fn$ begin if new.entity=''transacoes'' then raise exception ''Injected failure'' using errcode=''P0002''; end if; return new; end $fn$';
 execute 'create trigger test_fail_payment_audit before insert on public.audit_logs for each row execute function private.test_fail_payment_audit()';
 cmd=gen_random_uuid();execute 'set local role authenticated';
 begin perform public.save_financial_entry(org,cmd,jsonb_build_object('operation','settle','id',entry,'version',1,'paid_date','2026-01-15','settlement_amount','10.00')); raise exception 'Injected payment failure ignored'; exception when no_data_found then null; end;
 execute 'reset role';
 if (select paid_amount from public.transacoes where id=entry)<>0 or (select count(*) from public.financial_payments)<>m or (select count(*) from public.audit_logs)<>a or exists(select 1 from private.financial_entry_commands where request_id=cmd) then raise exception 'Partial payment persisted on failure'; end if;
 execute 'drop trigger test_fail_payment_audit on public.audit_logs';execute 'drop function private.test_fail_payment_audit()';
 update public.user_roles set role_id='viewer' where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 perform public.get_financial_payments(org,entry,1);
 begin perform public.save_financial_entry(org,gen_random_uuid(),body); raise exception 'Viewer writes plan'; exception when insufficient_privilege then null; end;
 begin update public.financial_payments set amount=1 where entry_id=entry; raise exception 'Direct payment write allowed'; exception when insufficient_privilege then null; end;
 begin perform public.get_financial_payments(gen_random_uuid(),entry,1); raise exception 'Foreign organization reads payments'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 update public.organization_members set active=false where organization_id=org and user_id=actor;
 execute 'set local role authenticated';
 if exists(select 1 from public.financial_payments) or exists(select 1 from public.financial_installment_plans) then raise exception 'Revoked access leaked data'; end if;
 execute 'reset role';execute 'set local role anon';
 begin perform 1 from public.financial_payments; raise exception 'Anonymous reads payments'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 execute 'set constraints all immediate';
end $test$;
rollback;
select 'PASS: partial/full payments, immutable journal, exact installments, month end, idempotency, stale version, overpayment rejection, deferred invariants, atomic failure rollback and RLS; tests rolled back' as result;
