export function parseCSV(source:string):string[][]{
 const input=source.replace(/^\uFEFF/,'');const first=input.split(/\r?\n/,1)[0];const delimiter=first.split(';').length>first.split(',').length?';':',';
 const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;
 for(let i=0;i<input.length;i++){const c=input[i];if(c==='"'){if(quoted&&input[i+1]==='"'){cell+='"';i++;}else if(quoted||cell==='')quoted=!quoted;else cell+=c;}else if(c===delimiter&&!quoted){row.push(cell.trim());cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&input[i+1]==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}
 if(quoted)throw new Error('CSV com aspas incompletas.');row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length>5001)throw new Error('Importe até 5.000 linhas por arquivo.');return rows;
}
export function normalizedNumber(value:string){const s=value.trim().replace(/^R\$\s*/,'').replace(/\s/g,'');if(s.includes(','))return s.replaceAll('.','').replace(',','.');return s;}
export function normalizedDate(value:string){const s=value.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;if(/^\d{2}\/\d{2}\/\d{4}$/.test(s))return s.split('/').reverse().join('-');if(/^\d{5}(\.0+)?$/.test(s)){const date=new Date(Date.UTC(1899,11,30)+Number(s)*86400000);return date.toISOString().slice(0,10);}return s;}
export function mappedRows(rows:string[][],mapping:Record<string,string>){return rows.slice(1).map(cells=>Object.fromEntries(Object.entries(mapping).filter(([,index])=>index!=='').map(([key,index])=>[key,cells[Number(index)]??''])));}
// XLSX is a ZIP of XML worksheets. Read cell values only, never execute formulas/macros.
export async function readXLSX(buffer:ArrayBuffer):Promise<string[][]>{
 const bytes=new Uint8Array(buffer),view=new DataView(buffer);const files=new Map<string,{offset:number;size:number;raw:number;method:number}>();let end=-1;
 for(let i=bytes.length-22;i>=Math.max(0,bytes.length-65557);i--)if(view.getUint32(i,true)===0x06054b50){end=i;break;}
 if(end<0)throw new Error('Arquivo XLSX inválido.');let at=view.getUint32(end+16,true);const count=view.getUint16(end+10,true);if(count>2000)throw new Error('Planilha muito grande.');
 for(let n=0;n<count;n++){if(at+46>bytes.length||view.getUint32(at,true)!==0x02014b50)throw new Error('Estrutura XLSX inválida.');const nameLength=view.getUint16(at+28,true),extra=view.getUint16(at+30,true),comment=view.getUint16(at+32,true);const name=new TextDecoder().decode(bytes.slice(at+46,at+46+nameLength));files.set(name,{offset:view.getUint32(at+42,true),size:view.getUint32(at+20,true),raw:view.getUint32(at+24,true),method:view.getUint16(at+10,true)});at+=46+nameLength+extra+comment;}
 let budget=0;async function xml(name:string){const entry=files.get(name);if(!entry)return null;if(entry.raw>10000000||budget+entry.raw>20000000)throw new Error('Planilha excede o limite de leitura.');budget+=entry.raw;const offset=entry.offset;if(offset+30>bytes.length||view.getUint32(offset,true)!==0x04034b50)throw new Error('Planilha inválida.');const start=offset+30+view.getUint16(offset+26,true)+view.getUint16(offset+28,true);if(start+entry.size>bytes.length)throw new Error('Planilha incompleta.');const part=bytes.slice(start,start+entry.size);let output:Uint8Array=part;
  if(entry.method===8){const stream=new Blob([part]).stream().pipeThrough(new DecompressionStream('deflate-raw'));const reader=stream.getReader();const chunks:Uint8Array[]=[];let total=0;while(true){const r=await reader.read();if(r.done)break;total+=r.value.length;if(total>10000000){await reader.cancel();throw new Error('Planilha excede o limite.');}chunks.push(r.value);}output=new Uint8Array(total);let p=0;for(const c of chunks){output.set(c,p);p+=c.length;}}
  else if(entry.method!==0)throw new Error('Compressão de planilha não suportada.');
  const doc=new DOMParser().parseFromString(new TextDecoder().decode(output),'application/xml');if(doc.querySelector('parsererror'))throw new Error('XML da planilha inválido.');return doc;
 }
 const workbook=await xml('xl/workbook.xml'),relations=await xml('xl/_rels/workbook.xml.rels');const id=workbook?.getElementsByTagName('sheet')[0]?.getAttribute('r:id');const target=Array.from(relations?.getElementsByTagName('Relationship')??[]).find(r=>r.getAttribute('Id')===id)?.getAttribute('Target');if(!target)throw new Error('Nenhuma aba encontrada.');const sheetPath=target.startsWith('/')?target.slice(1):'xl/'+target.replace(/^\.\//,'');if(sheetPath.includes('..'))throw new Error('Caminho de aba inválido.');const shared=await xml('xl/sharedStrings.xml'),sheet=await xml(sheetPath);if(!sheet)throw new Error('Aba indisponível.');const strings=Array.from(shared?.getElementsByTagName('si')??[]).map(si=>Array.from(si.getElementsByTagName('t')).map(n=>n.textContent??'').join(''));
 const rows:string[][]=[];for(const r of Array.from(sheet.getElementsByTagName('row'))){if(rows.length>5000)throw new Error('Importe até 5.000 linhas.');const row:string[]=[];for(const c of Array.from(r.getElementsByTagName('c'))){const ref=c.getAttribute('r')??'';const letters=ref.match(/^[A-Z]+/)?.[0]??'A';let index=0;for(const char of letters)index=index*26+char.charCodeAt(0)-64;if(index>200)throw new Error('Máximo de 200 colunas.');const type=c.getAttribute('t');const v=c.getElementsByTagName('v')[0]?.textContent??'';row[index-1]=type==='s'?strings[Number(v)]??'':type==='inlineStr'?Array.from(c.getElementsByTagName('t')).map(t=>t.textContent??'').join(''):v;}if(row.some(Boolean))rows.push(Array.from({length:row.length},(_,i)=>row[i]??''));}return rows;
}
