import Link from "next/link";
import {z} from "zod";
import {requireAccess} from "@/services/access";
import {productsSchema,variantSchema,calculateProductCost} from "@/lib/products";
import {displayQuantity,displayUnitCost} from "@/lib/inputs";
import {formatMoney} from "@/lib/finance";
import {ProductForm,VariantForm} from "@/components/product-form";
import {Button} from "@/components/ui/button";
import {savedSaleEstimate} from "@/lib/calculators";
export const dynamic="force-dynamic";
export default async function Products({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const params=await searchParams;const q=(params.q??"").slice(0,100);const page=Math.min(100000,Math.max(1,parseInt(params.page??"1",10)||1));
 const {client,user,organizationId}=await requireAccess("operational.read");
 const [list,roles]=await Promise.all([client.rpc("get_products",{org:organizationId,search:q,page}),client.from("user_roles").select("role_id").eq("organization_id",organizationId).eq("user_id",user.id)]);
 if(list.error||roles.error)throw new Error("Não foi possível carregar os produtos.");
 const grants=await client.from("role_permissions").select("permission_id").in("role_id",(roles.data??[]).map(r=>r.role_id)).eq("permission_id","operational.write").limit(1);if(grants.error)throw new Error("Não foi possível verificar seu acesso.");const canWrite=!!grants.data?.length;
 const result=productsSchema.parse(list.data);let selected=result.items.find(p=>p.id===params.product);
 if(!selected&&z.uuid().safeParse(params.product).success){const r=await client.rpc("get_products",{org:organizationId,selected:params.product!,search:"",page:1});if(r.error)throw new Error("Não foi possível consultar o produto.");selected=productsSchema.parse(r.data).items[0];}
 const href=(extra:Record<string,string>={})=>"/produtos?"+new URLSearchParams({q,page:String(page),...extra});
 const detailHref=(extra:Record<string,string>={})=>href({product:selected!.id,...extra});
 let variants:z.infer<typeof variantSchema>[]=[];let materials:{id:string;name:string;sku:string;base_unit:string;active:boolean}[]=[];
 if(selected){const [v,m]=await Promise.all([client.rpc("get_product_variants",{org:organizationId,product:selected.id}),client.from("inputs").select("id,name,sku,base_unit,active").eq("organization_id",organizationId).order("name").limit(1001)]);if(v.error||m.error)throw new Error("Não foi possível carregar a ficha.");variants=z.array(variantSchema).parse(v.data);materials=m.data??[];}
 const variant=variants.find(v=>v.id===params.variant);const cost=variant?calculateProductCost(variant,selected?.minimum_margin):null;
 const sale=variant?savedSaleEstimate(variant.attributes,cost?.total??null,variant.price):null;
 const catalogVariants=new Map<string,z.infer<typeof variantSchema>[]>();
 if(!selected){await Promise.all(result.items.filter(p=>p.variant_count>0).map(async p=>{const r=await client.rpc("get_product_variants",{org:organizationId,product:p.id});if(r.error)throw new Error("Não foi possível carregar os custos do catálogo.");catalogVariants.set(p.id,z.array(variantSchema).parse(r.data));}));}
 return <main className="content finance-content">
  <p className="eyebrow">PRODUTOS</p><h1>{selected?selected.name:"Seus produtos, com custo real"}</h1><p className="text-zinc-500">{selected?"Monte as versões e veja quanto custa cada unidade vendida.":"Organize os itens que você vende e os materiais usados para produzi-los."}</p>
  {params.saved&&<p className="notice" role="status">Cadastro salvo. A ficha usa os custos atuais dos insumos.</p>}
  {params.product&&!selected&&<p className="notice" role="alert">Produto não encontrado.</p>}
  {!selected?<div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
   <section className="min-w-0 rounded-xl border border-zinc-200 bg-white p-6"><h2>Catálogo ({result.total})</h2><form className="mb-5 flex items-end gap-3"><label className="grow text-sm">Buscar nome ou código<input name="q" defaultValue={q} maxLength={100} className="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 px-3 py-2"/></label><Button>Buscar</Button></form>
    <div className="mb-5 flex flex-wrap gap-3 text-sm"><Link className="underline" href="/calculadoras?mode=ml">Novo pela calculadora Mercado Livre</Link><Link className="underline" href="/calculadoras?mode=3d">Novo pela calculadora 3D</Link></div>
    {!result.items.length?<p className="py-10 text-center text-sm text-zinc-500">Nenhum produto encontrado. Simule e salve pela calculadora ou cadastre ao lado.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-zinc-200 text-zinc-500"><tr><th className="pb-3">Peça / kit</th><th className="pb-3">Custo</th><th className="pb-3">Venda</th><th className="pb-3">Lucro estimado</th><th className="pb-3">Ações</th></tr></thead><tbody className="divide-y divide-zinc-100">{result.items.flatMap(p=>{const rows=catalogVariants.get(p.id)??[];return rows.length?rows.map(v=>{const c=calculateProductCost(v);const s=savedSaleEstimate(v.attributes,c.total,v.price);return <tr key={v.id}><td className="py-4 pr-4"><strong className="block font-medium">{p.name} · {v.name}</strong><span className="text-xs text-zinc-500">{v.sku}{!p.active||!v.active?" · Inativo":""}</span></td><td className="py-4 pr-3 whitespace-nowrap">{c.total===null?"Pendente":formatMoney(c.total)}</td><td className="py-4 pr-3 whitespace-nowrap">{formatMoney(v.price)}</td><td className="py-4 pr-3 whitespace-nowrap">{s?formatMoney(s.profit):"Configurar taxas"}{s&&<span className="block text-xs text-zinc-500">Margem {s.margin??"—"}%</span>}</td><td className="py-4"><Link className="underline" href={href({product:p.id,variant:v.id})}>Abrir ficha</Link><Link className="mt-2 block underline" href={`/calculadoras?mode=${Object.keys(v.production).length||v.attributes.calculator&&typeof v.attributes.calculator==="object"&&(v.attributes.calculator as Record<string,unknown>).mode==="3d"?"3d":"ml"}&product=${p.id}&variant=${v.id}`}>Simular / ajustar</Link></td></tr>;}):[<tr key={p.id}><td className="py-4 pr-4">{p.name}</td><td>Pendente</td><td>{formatMoney(p.default_sale_price)}</td><td>Sem ficha</td><td><Link className="underline" href={href({product:p.id})}>Criar versão</Link></td></tr>];})}</tbody></table></div>}
    <div className="mt-5 flex justify-between text-sm"><span>Página {page}</span><div className="flex gap-4">{page>1&&<Link href={href({page:String(page-1)})}>Anterior</Link>}{page*25<result.total&&<Link href={href({page:String(page+1)})}>Próxima</Link>}</div></div>
   </section><aside className="h-fit rounded-xl border border-zinc-200 bg-white p-6"><h2>Novo produto</h2>{canWrite?<ProductForm requestId={crypto.randomUUID()}/>:<p className="text-sm text-zinc-500">Seu perfil permite consultar os produtos.</p>}</aside>
  </div>:<>
   <nav className="mb-6 flex flex-wrap gap-4 text-sm"><Link className="underline" href={href()}>Todos os produtos</Link><Link className="underline" href="/insumos">Insumos</Link>{variant&&<><Link className="underline" href={`/calculadoras?mode=ml&product=${selected.id}&variant=${variant.id}`}>Simular venda Mercado Livre</Link><Link className="underline" href={`/calculadoras?mode=3d&product=${selected.id}&variant=${variant.id}`}>Simular produção 3D</Link></>}</nav>
   {!selected.active&&<p className="notice">Produto inativo. Reative no cadastro para alterar suas versões.</p>}
   <div className="grid gap-6 xl:grid-cols-[320px_minmax(0,1fr)]">
    <aside className="grid h-fit gap-6"><section className="rounded-xl border border-zinc-200 bg-white p-5"><h2>Versões / SKUs</h2><p className="text-xs text-zinc-500">Use Padrão para um produto único. Cores e kits podem ter fichas próprias.</p><ul className="space-y-2">{variants.map(v=><li key={v.id}><Link className={"block rounded-lg border p-3 text-sm "+(variant?.id===v.id?"border-zinc-900 bg-zinc-50":"border-zinc-200")} href={detailHref({variant:v.id})}><strong className="block font-medium">{v.name}{!v.active&&" · Inativa"}</strong><span className="text-xs text-zinc-500">{v.sku} · {formatMoney(v.price)}</span></Link></li>)}</ul>{!variants.length&&<p className="text-sm text-zinc-500">Crie a primeira versão ao lado.</p>}{canWrite&&selected.active&&variants.length<100&&<Button asChild variant="outline" className="mt-4"><Link href={detailHref()}>Nova versão</Link></Button>}</section>
     <details className="rounded-xl border border-zinc-200 bg-white p-5"><summary className="cursor-pointer text-sm font-medium">Editar cadastro do produto</summary><div className="mt-5">{canWrite?<ProductForm key={selected.id+selected.version} record={selected} requestId={crypto.randomUUID()}/>:<p className="text-sm">{selected.description||"Sem descrição"}</p>}</div></details>
    </aside>
    <div className="min-w-0 space-y-6">
     {cost&&variant&&<section className="rounded-xl border border-zinc-200 bg-white p-6"><p className="eyebrow">CUSTO POR UNIDADE VENDIDA</p><div className="flex flex-wrap justify-between gap-4"><div><h2 className="mb-2 text-3xl">{cost.total===null?"Ficha incompleta":formatMoney(cost.total)}</h2><p className="mb-4 text-sm text-zinc-500">Preço: {formatMoney(variant.price)} · {cost.grossMargin!==null?`Margem antes de taxas: ${cost.grossMargin.replace(".",",")}%`:"Margem ainda não calculada"}</p></div>{cost.belowMinimum&&<p className="text-sm font-medium text-amber-700">Abaixo da margem mínima de {displayQuantity(selected.minimum_margin)}%</p>}</div>
      {sale&&<p className="notice">Lucro estimado após custos e taxas informados: <strong>{formatMoney(sale.profit)}</strong> · Margem {sale.margin??"—"}%</p>}
      {cost.issues.length>0&&<ul className="mb-4 list-disc space-y-1 pl-5 text-sm text-amber-800">{cost.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>}
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-zinc-200 text-zinc-500"><tr><th className="pb-2">Composição</th><th className="pb-2">Consumo com perdas</th><th className="pb-2 text-right">Custo (R$)</th></tr></thead><tbody className="divide-y divide-zinc-100">{cost.lines.map((line,i)=><tr key={i}><td className="py-2 pr-3">{line.label}</td><td className="py-2 pr-3 whitespace-nowrap">{line.quantity?displayQuantity(line.quantity)+" "+line.unit:"—"}</td><td className="py-2 text-right whitespace-nowrap">{line.amount===null?"Pendente":displayUnitCost(line.amount)}</td></tr>)}</tbody></table></div>
      <p className="mt-4 mb-0 text-xs text-zinc-500">Estimativa com custos atuais, antes de comissão, frete da venda e tributos. O custo total é arredondado para centavos na exibição; os componentes preservam até seis casas. Esta ficha não representa lucro líquido.</p>
     </section>}
     <section className="rounded-xl border border-zinc-200 bg-white p-6"><h2>{variant?"Ficha · "+variant.name:"Nova versão e ficha de custo"}</h2>{params.variant&&!variant&&<p className="notice">Versão não encontrada neste produto.</p>}{materials.length>1000&&<p className="notice">O seletor mostra os primeiros 1.001 insumos em ordem alfabética.</p>}{canWrite&&selected.active?<VariantForm key={(variant?.id??"new")+String(variant?.version??0)} product={selected} record={variant} materials={materials} requestId={crypto.randomUUID()}/>:<p className="text-sm text-zinc-500">{!selected.active?"Reative o produto para editar a ficha.":"Seu perfil permite consultar as fichas."}</p>}</section>
    </div>
   </div>
  </>}
 </main>;
}
