import Link from "next/link";
import {z} from "zod";
import Decimal from "decimal.js";
import {requireAccess} from "@/services/access";
import {CalculatorForm} from "@/components/calculator-form";
import {calculatorDefaults} from "@/lib/calculators";
import {productsSchema,variantSchema,failurePercent,calculateProductCost} from "@/lib/products";
export const dynamic="force-dynamic";
export default async function Calculators({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const params=await searchParams;const mode=params.mode==="3d"?"3d":"ml";
 const {client,user,organizationId}=await requireAccess("operational.read");const [m,roles]=await Promise.all([client.rpc("get_calculator_materials",{org:organizationId}),client.from("user_roles").select("role_id").eq("organization_id",organizationId).eq("user_id",user.id)]);if(m.error||roles.error)throw new Error("Não foi possível carregar a calculadora.");
 const materials=z.array(z.object({id:z.uuid(),name:z.string(),base_unit:z.string(),active:z.boolean()})).parse(m.data);
 const grants=await client.from("role_permissions").select("permission_id").in("role_id",(roles.data??[]).map(r=>r.role_id)).eq("permission_id","operational.write").limit(1);if(grants.error)throw new Error("Não foi possível verificar seu acesso.");
 let product:z.infer<typeof productsSchema>["items"][number]|undefined;let variant:z.infer<typeof variantSchema>|undefined;
 if(params.product||params.variant){if(!z.uuid().safeParse(params.product).success||!z.uuid().safeParse(params.variant).success)throw new Error("Produto inválido.");const [p,v]=await Promise.all([client.rpc("get_products",{org:organizationId,selected:params.product!,search:"",page:1}),client.rpc("get_product_variants",{org:organizationId,product:params.product!})]);if(p.error||v.error)throw new Error("Não foi possível abrir o produto.");product=productsSchema.parse(p.data).items[0];variant=z.array(variantSchema).parse(v.data).find(v=>v.id===params.variant);if(!product||!variant)throw new Error("Produto não encontrado.");}
 let initial:Record<string,string>={...calculatorDefaults,mode,...(mode==="3d"?{price:"0",commission:"0"}:{})};
 if(variant){const stored=z.record(z.string(),z.string()).safeParse(variant.attributes.calculator);if(stored.success)initial={...initial,...stored.data,mode};initial.price=variant.price;initial.cost=variant.other_direct_costs;
  if(Object.keys(variant.production).length){const p=variant.production;initial={...initial,filament_id:p.filament_id,weight:p.piece_weight_g,support:p.support_weight_g,purge:p.purge_weight_g,batch:p.quantity_per_batch,hours:new Decimal(p.print_time_minutes).div(60).floor().toFixed(0),minutes:new Decimal(p.print_time_minutes).mod(60).toFixed(),watts:p.printer_power_watts,energy:p.electricity_price_kwh,machine_hour:p.machine_hour_cost,maintenance:p.maintenance_cost_per_hour,labor_hour:p.labor_hour_cost,failure:failurePercent(p.failed_print_rate)};if(!stored.success||!new Decimal(initial.labor_setup||0).plus(initial.labor_post||0).plus(initial.labor_pack||0).eq(p.labor_minutes)){initial.labor_setup=p.labor_minutes;initial.labor_post='0';initial.labor_pack='0';}if(!stored.success||!new Decimal(initial.extra_batch||0).div(initial.batch||1).plus(initial.extra_unit||0).toDecimalPlaces(6).eq(variant.other_direct_costs)){initial.extra_batch='0';initial.extra_unit=variant.other_direct_costs;}if(initial.machine_mode==='derived'&&(!new Decimal(initial.machine_purchase||0).minus(initial.machine_residual||0).div(initial.machine_lifetime||1).toDecimalPlaces(6).eq(p.machine_hour_cost)))initial.machine_mode='direct';if(mode==="ml")initial.cost=calculateProductCost(variant).total??"0";}
 }
 const suffix=product&&variant?`&product=${product.id}&variant=${variant.id}`:"";
 return <main className="content finance-content"><p className="eyebrow">CALCULADORAS</p><h1>{mode==="ml"?"Mercado Livre · custo e lucro":"Produção 3D · custo e operação"}</h1><p className="text-zinc-500">Simule por peça ou kit e salve o resultado no produto. Ajuste os parâmetros quando precisar.</p><nav className="mb-6 flex flex-wrap gap-3 text-sm"><Link className={"rounded-lg border px-4 py-2 "+(mode==="ml"?"bg-zinc-900 text-white":"bg-white")} href={"/calculadoras?mode=ml"+suffix}>Calculadora Mercado Livre</Link><Link className={"rounded-lg border px-4 py-2 "+(mode==="3d"?"bg-zinc-900 text-white":"bg-white")} href={"/calculadoras?mode=3d"+suffix}>Calculadora 3D</Link><Link className="px-4 py-2 underline" href="/produtos">Produtos</Link></nav>{variant&&<p className="notice">Ajustando {product!.name} · {variant.name}. Salvar atualiza esta versão.</p>}{materials.length>1000&&<p className="notice">O seletor está limitado aos primeiros 1.001 insumos.</p>}<CalculatorForm key={mode+(variant?.id??"new")+(variant?.version??0)} mode={mode} initial={initial} materials={materials} parts={variant?.components} productId={product?.id} variantId={variant?.id} version={variant?.version} name={product?.name} sku={variant?.sku} variantName={variant?.name} requestId={crypto.randomUUID()} organizationId={organizationId} canWrite={!!grants.data?.length} hasProduction={!!variant&&Object.keys(variant.production).length>0}/></main>;
}

