import {test} from "node:test";
import assert from "node:assert/strict";
import {calculatorDefaults,parseCalculator,saleEstimate,machineHourly,productionParameters,extraUnitCost,capacityEstimate,savedSaleEstimate} from "../src/lib/calculators.ts";
import {calculateProductCost,type Variant} from "../src/lib/products.ts";
const ml=()=>parseCalculator({...calculatorDefaults,price:"100",cost:"30",commission:"12",tax:"6",fixed_fee:"6",shipping:"10",packaging:"2",acos:"10",ads_share:"50",monthly_units:"100",monthly_fixed:"200"});
test("Mercado Livre reúne taxas, logística e ACOS ponderado",()=>{const s=saleEstimate("30",ml());assert.equal(s.total,"71.000000");assert.equal(s.profit,"29.000000");assert.equal(s.margin,"29.00");assert.equal(s.breakEven,"62.34");assert.equal(s.idealPrice,"84.22");assert.equal(s.monthlyRevenue,"10000.00");assert.equal(s.monthlyProfit,"2700.00");});
test("preço alvo é inviável com taxas e margem >=100%, sem divisão por zero",()=>{const v={...ml(),commission:"80",tax:"20",acos:"0"};const s=saleEstimate("30",v);assert.equal(s.breakEven,null);assert.equal(s.idealPrice,null);assert.equal(s.profit,"-48.000000");assert.equal(saleEstimate("0",{...ml(),price:"0"}).roi,null);assert.throws(()=>saleEstimate("30",{...ml(),reimbursement:"11"}));});
test("campos de fronteira e precisão são validados",()=>{for(const changes of [{price:"1.234"},{price:"-1"},{commission:""},{ads_share:"101"},{monthly_units:"1.5"},{hours_day:"25"},{days_month:"32"},{minutes:"60"}] as Record<string,string>[])assert.throws(()=>parseCalculator({...ml(),...changes}));assert.equal(parseCalculator({...ml(),cost:"0,000001"}).cost,"0.000001");});
test("custo 3D de lote, depreciação, labor ativo e extras reconciliam",()=>{
 const v=parseCalculator({...calculatorDefaults,mode:"3d",price:"20",commission:"0",weight:"100",support:"10",purge:"10",batch:"2",filament_kg:"75",hours:"2",watts:"200",energy:"1",failure:"10",machine_mode:"derived",machine_purchase:"2500",machine_residual:"500",machine_lifetime:"1000",maintenance:"0.5",labor_setup:"10",labor_post:"10",labor_pack:"10",labor_hour:"20",extra_batch:"2",extra_unit:"0.2"});
 assert.equal(machineHourly(v),"2.000000");assert.equal(extraUnitCost(v),"1.200000");
 const variant:Variant={id:"qa",name:"qa",sku:"qa",price:"20",active:true,version:1,attributes:{},production:productionParameters(v),other_direct_costs:extraUnitCost(v),overhead_percentage:"0",filament:{id:"qa",name:"PETG",base_unit:"g",average_cost:"0.075",active:true,version:1},components:[]};
 assert.equal(calculateProductCost(variant).total,"13.900000");
 assert.throws(()=>machineHourly({...v,machine_lifetime:"0"}));assert.throws(()=>machineHourly({...v,machine_residual:"3000"}));for(const changes of [{failure:"100"},{batch:"0"},{batch:"1.5"}] as Record<string,string>[])assert.throws(()=>parseCalculator({...v,...changes}));
});
test("capacidade limita a produção à disponibilidade e protege tempo zero",()=>{const v={...ml(),hours:"2",minutes:"0",batch:"2",printers:"2",hours_day:"8",days_month:"20",availability:"50",monthly_units:"200",monthly_fixed:"100",income_goal:"1000"};const c=capacityEstimate(v,"5")!;assert.equal(c.capacity,"160");assert.equal(c.deliverable,"160");assert.equal(c.load,"125.0");assert.equal(c.monthlyResult,"700.00");assert.equal(c.goalGap,"300.00");assert.equal(capacityEstimate({...v,hours:"0"},"5"),null);});
test("parâmetros salvos reavaliam lucro com custo e preço atuais",()=>{assert.equal(savedSaleEstimate({calculator:ml()},"40","100")?.profit,"19.000000");assert.equal(savedSaleEstimate({calculator:ml()},null,"100"),null);assert.equal(savedSaleEstimate({calculator:{commission:"inválido"}},"40","100"),null);assert.ok(JSON.stringify({calculator:ml(),manual_cost_confirmed:true}).length<2000);});

