import {createServerClient} from '@supabase/ssr';
import assert from 'node:assert/strict';
const jar=new Map();
const client=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{cookies:{getAll:()=>[...jar].map(([name,value])=>({name,value})),setAll:values=>values.forEach(({name,value})=>jar.set(name,value))}});
const {error}=await client.auth.signInWithPassword({email:process.env.BE_TEST_EMAIL,password:process.env.BE_TEST_PASSWORD});
assert.equal(error,null);
const cookie=[...jar].map(([name,value])=>name+'='+value).join('; ');
const root=await fetch('http://127.0.0.1:3000/',{headers:{cookie},redirect:'manual'});
assert.equal(root.status,200,'authenticated home renders');
const html=await root.text();assert.ok(html.includes('ACESSO ATIVO'),'home recognizes authorized membership');
const files=await client.from('attachments').select('id').eq('state','confirmed').limit(1);
assert.equal(files.error,null);assert.equal(files.data.length,1);
const download=await fetch('http://127.0.0.1:3000/documents/'+files.data[0].id,{headers:{cookie},redirect:'manual'});
assert.equal(download.status,200);assert.equal(download.headers.get('cache-control'),'private, no-store');
assert.equal(download.headers.get('content-type'),'image/png');
const unauthenticated=await fetch('http://127.0.0.1:3000/',{redirect:'manual'});assert.ok([303,307].includes(unauthenticated.status));
assert.ok(unauthenticated.headers.get('location').includes('/login'));
await client.auth.signOut({scope:'local'});
console.log('PASS: authenticated home, active administrator, private download, no-cache and anonymous redirect.');

