"use client";
import {useActionState,useEffect,useState} from "react";
import {runCalculator,type CalculatorState} from "@/app/calculadoras/actions";
import {calculatorDefaults} from "@/lib/calculators";
import {compatibleUnits} from "@/lib/inputs";
import {formatMoney} from "@/lib/finance";
import {Button} from "@/components/ui/button";
type Material={id:string;name:string;base_unit:string;active:boolean};
type Part={input_id:string;quantity:string;unit:string;waste_percentage:string};
const field="mt-1 block min-h-11 w-full rounded-lg border border-zinc-300 bg-white px-3 py-2 text-sm";
const profileKeys=["commission","tax","fixed_fee","shipping","packaging","outsourced","storage","collection","reimbursement","acos","ads_share","target_margin","ad_type","logistics","filament_kg","watts","energy","machine_mode","machine_hour","machine_purchase","machine_residual","machine_lifetime","maintenance","labor_hour","failure","printers","hours_day","days_month","availability","monthly_fixed","income_goal"];
export function CalculatorForm({mode,initial,materials,parts:initialParts=[],productId="",variantId="",version=1,name="",sku="",variantName="Padrão",requestId,organizationId,canWrite,hasProduction=false}:{mode:"ml"|"3d";initial:Record<string,string>;materials:Material[];parts?:Part[];productId?:string;variantId?:string;version?:number;name?:string;sku?:string;variantName?:string;requestId:string;organizationId:string;canWrite:boolean;hasProduction?:boolean}){
 const [values,setValues]=useState<Record<string,string>>({...calculatorDefaults,...initial,mode});const [parts,setParts]=useState(initialParts.map((p,i)=>({...p,key:String(i)})));const [state,action,pending]=useActionState<CalculatorState,FormData>(runCalculator,{message:""});const [dirty,setDirty]=useState(false);const [notice,setNotice]=useState("");
 const storageKey=`bueno-calculator:${organizationId}:${mode}`;
 useEffect(()=>{if(variantId)return;try{const saved=JSON.parse(localStorage.getItem(storageKey)??"{}");setValues(v=>({...v,...Object.fromEntries(profileKeys.filter(k=>typeof saved[k]==="string").map(k=>[k,saved[k]]))}));}catch{/* A blocked browser store does not block calculation. */}},[storageKey,variantId]);
 useEffect(()=>{setDirty(false);},[state]);
 const change=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));setDirty(true);};
 const number=(key:string,label:string,placeholder="0",disabled=false)=><label key={key} className="text-sm font-medium">{label}<input className={field} name={key} inputMode="decimal" maxLength={18} placeholder={placeholder} readOnly={disabled} value={values[key]} onChange={e=>change(key,e.target.value)}/></label>;
 const select=(key:string,label:string,options:[string,string][])=><label className="text-sm font-medium">{label}<select className={field} name={key} value={values[key]} onChange={e=>change(key,e.target.value)}>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>;
 const visible=new Set<string>(["mode","price","commission","tax","fixed_fee","shipping","packaging","outsourced","storage","collection","reimbursement","acos","ads_share","target_margin","monthly_units","monthly_fixed","ad_type","logistics"]);
 if(mode==="ml")visible.add("cost");else for(const k of ["filament_id","filament_kg","weight","support","purge","batch","hours","minutes","watts","energy","machine_mode","machine_hour","machine_purchase","machine_residual","machine_lifetime","maintenance","labor_setup","labor_post","labor_pack","labor_hour","failure","extra_batch","extra_unit","printers","hours_day","days_month","availability","income_goal"])visible.add(k);
 return <form action={action} className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_350px]">
  <input type="hidden" name="mode" value={mode}/><input type="hidden" name="product_id" value={productId}/><input type="hidden" name="variant_id" value={variantId}/><input type="hidden" name="version" value={version}/><input type="hidden" name="request_id" value={requestId}/>
  {Object.keys(calculatorDefaults).filter(k=>!visible.has(k)).map(k=><input key={k} type="hidden" name={k} value={values[k]}/>)}
  <div className="grid gap-5">
   <section className="rounded-xl border border-zinc-200 bg-white p-6"><h2>{mode==="ml"?"Custo e preço de venda":"Peça ou kit · lote de impressão"}</h2><div className="grid gap-4 sm:grid-cols-2">{mode==="ml"?number("cost",hasProduction?"Custo vem da ficha 3D salva":"Custo de compra / outros custos (R$)","0,00",hasProduction):<>{number("weight","Peso das peças do lote (g)")}{number("batch","Peças ou kits vendáveis por lote")}{number("hours","Horas de impressão do lote")}{number("minutes","Minutos adicionais (0–59)")}{select("filament_id","Filamento do estoque",[["","Preço manual por kg"],...materials.filter(m=>m.active&&["g","kg"].includes(m.base_unit)).map(m=>[m.id,m.name] as [string,string])])}{number("filament_kg",values.filament_id?"Preço manual ignorado (usa custo do insumo)":"Preço do filamento (R$/kg)","Ex.: 75,00")}</>}{number("price","Preço de venda por peça / kit (R$)","0,00")}{number("target_margin","Margem desejada sobre a venda (%)")}</div>{mode==="3d"&&<p className="mt-3 mb-0 text-xs text-zinc-500">Pesos e tempos são do lote inteiro. Para kit, informe quantos kits esse lote produz. O resultado é por unidade vendável.</p>}</section>
   {mode==="3d"&&<details className="rounded-xl border border-zinc-200 bg-white p-6" open><summary className="cursor-pointer font-medium">Configuração da operação 3D</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{number("watts","Potência média da impressora (W)")}{number("energy","Energia (R$/kWh)")}{number("support","Suportes do lote (g)")}{number("purge","Purga do lote (g)")}{number("failure","Falhas de impressão (%)")}{select("machine_mode","Custo da máquina",[["direct","Informar custo por hora"],["derived","Calcular pela compra e vida útil"]])}{number("machine_hour","Máquina (R$/h) — modo direto", "0",values.machine_mode!=="direct")}{number("machine_purchase","Preço da máquina (R$) — modo calculado")}{number("machine_residual","Valor residual da máquina (R$)")}{number("machine_lifetime","Vida útil produtiva estimada (horas)")}{number("maintenance","Manutenção (R$/h)")}{number("labor_hour","Mão de obra (R$/h)")}{number("labor_setup","Preparação do lote (min)")}{number("labor_post","Acabamento do lote (min)")}{number("labor_pack","Embalagem do lote (min)")}{number("extra_batch","Outros custos por lote (R$)")}{number("extra_unit","Outros custos por peça / kit (R$)")}</div><p className="mt-3 mb-0 text-xs text-zinc-500">Mão de obra é trabalho humano ativo. Falhas ajustam somente filamento. Valores zero significam que você optou por não considerar esse custo.</p></details>}
   <details className="rounded-xl border border-zinc-200 bg-white p-6" open={parts.length>0}><summary className="cursor-pointer font-medium">Materiais vinculados · argolas, embalagens e acessórios</summary><p className="mt-3 text-xs text-zinc-500">Consumo por peça ou kit vendido. Estes vínculos ficam na ficha para o controle de estoque; simular ou salvar ainda não faz baixa. Não repita o filamento selecionado acima.</p><div className="grid gap-3">{parts.map((part,i)=><div key={part.key} className="rounded-lg border border-zinc-200 p-3"><select aria-label={`Material ${i+1}`} className={field} name="component_id" required value={part.input_id} onChange={e=>{setParts(rows=>rows.map((r,j)=>j===i?{...r,input_id:e.target.value,unit:materials.find(m=>m.id===e.target.value)?.base_unit??"unidade"}:r));setDirty(true);}}><option value="">Selecione</option>{materials.filter(m=>m.active||m.id===part.input_id).map(m=><option key={m.id} value={m.id}>{m.name}{!m.active?" (inativo)":""}</option>)}</select><div className="mt-2 grid grid-cols-3 gap-2"><label className="text-xs">Quantidade<input className={field} name="component_quantity" inputMode="decimal" required value={part.quantity} onChange={e=>{setParts(rows=>rows.map((r,j)=>j===i?{...r,quantity:e.target.value}:r));setDirty(true);}}/></label><label className="text-xs">Unidade<select className={field} name="component_unit" value={part.unit} onChange={e=>{setParts(rows=>rows.map((r,j)=>j===i?{...r,unit:e.target.value}:r));setDirty(true);}}>{compatibleUnits(materials.find(m=>m.id===part.input_id)?.base_unit??part.unit).map(u=><option key={u}>{u}</option>)}</select></label><label className="text-xs">Perda (%)<input className={field} name="component_waste" inputMode="decimal" value={part.waste_percentage} onChange={e=>{setParts(rows=>rows.map((r,j)=>j===i?{...r,waste_percentage:e.target.value}:r));setDirty(true);}}/></label></div><button type="button" className="mt-2 text-xs text-red-700 underline" onClick={()=>{setParts(rows=>rows.filter((_,j)=>j!==i));setDirty(true);}}>Remover</button></div>)}</div><Button className="mt-3" type="button" variant="outline" disabled={!materials.some(m=>m.active)||parts.length>=100} onClick={()=>{setParts(rows=>[...rows,{key:crypto.randomUUID(),input_id:"",quantity:"1",unit:"unidade",waste_percentage:"0"}]);setDirty(true);}}>Adicionar material</Button>{!materials.length&&<p className="mt-3 text-xs text-zinc-500">Você pode simular com custos manuais agora e vincular os materiais após cadastrá-los em Insumos.</p>}</details>
   <section className="rounded-xl border border-zinc-200 bg-white p-6"><h2>Mercado Livre · custos da venda</h2><p className="text-xs text-zinc-500">Informe as taxas e o frete da sua operação. Clássico/Premium e modalidade são identificações; não preenchem tarifas automaticamente.</p><div className="grid gap-4 sm:grid-cols-2">{select("ad_type","Tipo de anúncio",[["classico","Clássico"],["premium","Premium"]])}{select("logistics","Modalidade",[["standard","Padrão / Coleta"],["flex","Flex"],["full","Full"],["full_super","Full Super"]])}{number("commission","Comissão (%) — informar")}{number("fixed_fee","Tarifa fixa por venda (R$)")}{number("tax","Impostos sobre venda (%)")}{number("shipping","Frete pago pelo vendedor (R$)")}</div><details className="mt-5"><summary className="cursor-pointer text-sm">Embalagem adicional, Full/Flex e publicidade</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{number("packaging","Embalagem adicional da venda (R$)")}{number("outsourced","Terceirização / transportadora (R$)")}{number("storage","Armazenagem por unidade (R$)")}{number("collection","Coleta / envio ao Full por unidade (R$)")}{number("reimbursement","Reembolso logístico (R$)")}{number("acos","ACOS das vendas por anúncios (%)")}{number("ads_share","Vendas originadas de anúncios (%)")}</div></details></section>
   <details className="rounded-xl border border-zinc-200 bg-white p-6"><summary className="cursor-pointer font-medium">Visão macro da operação · mês</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{number("monthly_units","Peças / kits planejados no mês")}{number("monthly_fixed","Custos fixos mensais adicionais (R$)")}{mode==="3d"&&<>{number("printers","Quantidade de impressoras")}{number("hours_day","Horas por impressora / dia")}{number("days_month","Dias de produção / mês")}{number("availability","Disponibilidade das máquinas (%)")}{number("income_goal","Meta de resultado mensal (R$)")}</>}</div><p className="mt-3 mb-0 text-xs text-zinc-500">Projeção, sem vendas registradas. Custos fixos aqui devem excluir o que já foi incluído no custo unitário.</p></details>
  </div>
  <aside className="grid gap-4 xl:sticky xl:top-5"><section className="rounded-xl border border-zinc-200 bg-white p-5"><h2>Resultado por peça / kit</h2><Button className="w-full" name="intent" value="simulate" disabled={pending}>{pending?"Calculando…":"Calcular"}</Button>{state.message&&<p className="notice mt-4" role="status">{state.message}</p>}{dirty&&state.result&&<p className="mt-3 text-sm text-amber-700">Valores alterados. Clique em Calcular para atualizar.</p>}{state.result&&<div className={dirty?"opacity-60":""}><dl className="mt-4 grid grid-cols-2 gap-3 text-sm">{[["Custo do produto",state.result.sale.cost],["Venda",state.result.sale.price],["Lucro estimado",state.result.sale.profit],["Preço para margem alvo",state.result.sale.idealPrice],["Preço de equilíbrio",state.result.sale.breakEven]].map(([label,value])=><div key={label!}><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 font-semibold">{value===null?"Inviável":formatMoney(value!)}</dd></div>)}<div><dt className="text-xs text-zinc-500">Margem após custos</dt><dd>{state.result.sale.margin?.replace(".",",")??"—"}%</dd></div></dl><details className="mt-4"><summary className="cursor-pointer text-sm">Composição dos custos</summary>{[...state.result.lines,...state.result.sale.lines.filter(l=>l.label!=="Custo do produto")].map((l,i)=><p key={i} className="mt-2 mb-0 flex justify-between gap-2 text-xs"><span>{l.label}</span><strong>{l.amount===null?"Pendente":formatMoney(l.amount)}</strong></p>)}</details><div className="mt-4 border-t border-zinc-200 pt-4 text-sm"><p>Faturamento planejado: <strong>{formatMoney(state.result.sale.monthlyRevenue)}</strong></p><p>Resultado mensal após fixos: <strong>{formatMoney(state.result.sale.monthlyProfit)}</strong></p>{state.result.capacity&&<><p>Capacidade estimada: <strong>{state.result.capacity.capacity} peças/kits por mês</strong></p><p>Carga planejada: {state.result.capacity.load??"—"}%</p><p>Resultado limitado à capacidade: <strong>{formatMoney(state.result.capacity.monthlyResult)}</strong></p><p>Falta para a meta: {formatMoney(state.result.capacity.goalGap)}</p></>}</div>{state.result.warnings.map(w=><p key={w} className="mt-3 text-xs text-amber-700">{w}</p>)}</div>}</section>
   <section className="rounded-xl border border-zinc-200 bg-white p-5"><h3>{variantId?"Atualizar produto":"Salvar como produto"}</h3><label className="text-sm">Nome do produto<input className={field} name="name" maxLength={200} defaultValue={name}/></label><label className="mt-3 block text-sm">SKU<input className={field} name="sku" maxLength={60} defaultValue={sku}/></label><label className="mt-3 block text-sm">Versão / peça ou kit<input className={field} name="variant_name" maxLength={100} defaultValue={variantName}/></label><Button className="mt-4 w-full" name="intent" value="save" disabled={pending||!canWrite}>Salvar cálculo e produto</Button><p className="mt-2 mb-0 text-xs text-zinc-500">Recalcula antes de salvar. Custos, preço e parâmetros ficam juntos no produto.</p></section>
   <button type="button" className="text-sm underline" onClick={()=>{try{localStorage.setItem(storageKey,JSON.stringify(Object.fromEntries(profileKeys.map(k=>[k,values[k]]))));setNotice("Parâmetros padrão salvos neste navegador.");}catch{setNotice("O navegador não permitiu salvar os parâmetros.");}}}>Usar parâmetros como padrão neste navegador</button>{notice&&<p role="status" className="text-xs">{notice}</p>}
  </aside>
 </form>;
}

