"use client";
import {useState} from 'react';
import {parseCSV,readXLSX,mappedRows} from '@/lib/tabular';
import {importBatch,type ImportResult} from '@/app/importacao/actions';
import type {Choice} from '@/lib/operations';
const columns:Record<string,[string,string,boolean][]>= {
 sales:[['order','Pedido',true],['sku','SKU interno',true],['date','Data',true],['quantity','Quantidade',true],['price','Preço unitário',true],['unit_cost','Custo histórico unitário',false],['fees','Taxas totais do pedido',false],['taxes','Impostos do pedido',false],['shipping','Frete da empresa',false],['shipping_income','Frete pago pelo cliente',false],['discount','Desconto do pedido',false],['other','Outras despesas do pedido',false],['expected','Repasse esperado',false],['due_date','Previsão de recebimento',false]],
 inputs:[['sku','SKU',true],['name','Nome',true],['unit','Unidade (g, kg, unidade…)',true],['minimum','Estoque mínimo',false],['category','Categoria',false],['supplier','Fornecedor',false]],
 purchases:[['reference','Referência única da compra/linha',true],['sku','SKU do insumo',true],['date','Data',true],['quantity','Quantidade',true],['unit','Unidade',true],['amount','Valor total dos materiais',true],['shipping','Frete',false],['supplier','Fornecedor',true]],
 receipts:[['reference','Referência única do repasse',true],['order','Pedido',true],['date','Data recebida',true],['amount','Valor recebido',true]],
 statement:[['reference','Identificador único da linha',true],['date','Data',true],['type','Tipo: receita ou despesa',true],['description','Descrição',true],['amount','Valor positivo',true]]
};
export function ImportForm({channels,accounts,categories}:{channels:Choice[];accounts:Choice[];categories:Choice[]}){
 const [kind,setKind]=useState('sales'),[rows,setRows]=useState<string[][]>([]),[mapping,setMapping]=useState<Record<string,string>>({}),[options,setOptions]=useState<Record<string,string>>({stock_mode:'stock',purchase_status:'none'}),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[results,setResults]=useState<ImportResult[]>([]);
 async function read(file:File|undefined){if(!file)return;setMessage('');setResults([]);try{if(file.size>5*1024*1024)throw new Error('Use arquivos de até 5 MB.');const parsed=file.name.toLowerCase().endsWith('.xlsx')?await readXLSX(await file.arrayBuffer()):parseCSV(await file.text());if(parsed.length<2)throw new Error('O arquivo precisa ter cabeçalho e dados.');setRows(parsed);const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');setMapping(Object.fromEntries(columns[kind].map(([key,label])=>{const i=parsed[0].findIndex(h=>normalize(h)===normalize(key)||normalize(h)===normalize(label));return [key,i<0?'':String(i)];})));}catch(e){setRows([]);setMessage(e instanceof Error?e.message:'Não foi possível ler o arquivo.');}}
 function selectOption(name:string,label:string,items:Choice[]){return <label className="op-label">{label}<select value={options[name]??''} onChange={e=>setOptions({...options,[name]:e.target.value})}><option value="">Selecione</option>{items.map(c=><option value={c.value} key={c.value}>{c.label}</option>)}</select></label>;}
 async function run(){const missing=columns[kind].filter(([key,,required])=>required&&mapping[key]===undefined||required&&mapping[key]==='');if(missing.length){setMessage('Associe todas as colunas obrigatórias.');return;}if(kind==='sales'&&options.stock_mode==='historical'&&!mapping.unit_cost){setMessage('Associe o custo histórico para importar vendas antigas.');return;}if(['sales','receipts'].includes(kind)&&!options.channel_id){setMessage('Selecione o canal.');return;}if((['receipts','statement'].includes(kind)||(kind==='purchases'&&options.purchase_status!=='none'))&&(!options.account_id||!options.category_id)){setMessage('Selecione conta e categoria financeira.');return;}setBusy(true);setResults([]);setMessage('Importando…');try{const data=mappedRows(rows,mapping);const groups=new Map<string,Record<string,string>[]>();data.forEach((r,i)=>{const key=kind==='sales'?r.order||String(i):String(i);groups.set(key,[...(groups.get(key)??[]),r]);});let batch:Record<string,string>[]=[];const all:ImportResult[]=[];for(const group of groups.values()){if(group.length>100){all.push({reference:group[0].order,status:'error',message:'Máximo de 100 itens por pedido.'});continue;}if(batch.length+group.length>100){all.push(...await importBatch(kind,batch,options));batch=[];setResults([...all]);}batch.push(...group);}if(batch.length)all.push(...await importBatch(kind,batch,options));setResults(all);setMessage(`Concluído: ${all.filter(r=>r.status==='imported').length} importados, ${all.filter(r=>r.status==='duplicate').length} duplicados, ${all.filter(r=>r.status==='error').length} com erro.`);}catch{setMessage('Importação interrompida. Os lotes já concluídos foram mantidos; você pode repetir o arquivo sem duplicar as referências.');}finally{setBusy(false);}}
 return <section className="op-card"><h2>Importar CSV ou Excel</h2><div className="op-fields"><label className="op-label">O que deseja importar<select disabled={busy} value={kind} onChange={e=>{setKind(e.target.value);setRows([]);setMapping({});setResults([]);}}>{[['sales','Vendas'],['inputs','Cadastro de insumos'],['purchases','Compras de insumos'],['receipts','Recebimentos'],['statement','Extrato financeiro']].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label className="op-label">Arquivo<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e=>read(e.target.files?.[0])}/></label>{['sales','receipts'].includes(kind)&&selectOption('channel_id','Canal de venda',channels)}{kind==='sales'&&selectOption('stock_mode','Movimentação dos produtos',[{value:'stock',label:'Baixar produtos prontos'},{value:'produce',label:'Produzir e vender'},{value:'historical',label:'Vendas antigas · sem movimentar estoque'}])}{kind==='purchases'&&selectOption('purchase_status','Registro financeiro',[{value:'none',label:'Somente estoque'},{value:'pending',label:'Gerar conta a pagar'},{value:'paid',label:'Compra já paga'}])}{(['receipts','statement'].includes(kind)||(kind==='purchases'&&options.purchase_status!=='none'))&&<>{selectOption('account_id','Conta financeira',accounts)}{selectOption('category_id','Categoria financeira',categories)}</>}</div><p className="op-help">Até 5.000 linhas e 5 MB. Excel: primeira aba, valores já calculados. Datas: AAAA-MM-DD ou DD/MM/AAAA. Valores aceitam vírgula decimal. Cada item usa o SKU interno do produto.</p>{kind==='statement'&&<p className="notice">Use extrato para movimentos ainda não registrados. Repasses de vendas devem entrar em Recebimentos; compras de insumos devem entrar em Compras, para evitar duplicação.</p>}
 {!!rows.length&&<><h3>Associe as colunas</h3><div className="op-fields">{columns[kind].map(([key,label,required])=><label className="op-label" key={key}>{label}{required?' *':''}<select disabled={busy} value={mapping[key]??''} onChange={e=>setMapping({...mapping,[key]:e.target.value})}><option value="">Não usar</option>{rows[0].map((header,index)=><option value={String(index)} key={index}>{header||'Coluna '+(index+1)}</option>)}</select></label>)}</div><h3 className="mt-6">Prévia · {rows.length-1} linhas</h3><div className="op-table"><table><thead><tr>{rows[0].map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{rows.slice(1,6).map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div><button className="op-button mt-5" disabled={busy} onClick={run}>{busy?'Importando…':'Confirmar importação'}</button></>}{message&&<p className="notice mt-5" role="status">{message}</p>}{results.length>0&&<div className="op-table"><table><thead><tr><th>Referência</th><th>Resultado</th></tr></thead><tbody>{results.map((r,i)=><tr key={i}><td>{r.reference}</td><td>{r.message}</td></tr>)}</tbody></table></div>}</section>;
}
