"use client";
import {useActionState,useState} from 'react';
import {operationAction} from '@/app/operacoes/actions';
import type {Field,Choice} from '@/lib/operations';
export function Fields({fields}:{fields:Field[]}){return <>{fields.map(f=><label key={f.name} className="op-label">{f.label}{f.type==='select'?<select name={f.name} defaultValue={f.value??''} required={f.required??true}>{!f.value&&<option value="">Selecione</option>}{f.choices?.map(c=><option value={c.value} key={c.value}>{c.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value} rows={2} maxLength={2000}/>:<input name={f.name} type={f.type==='date'?'date':'text'} inputMode={f.type==='number'?'decimal':undefined} defaultValue={f.value} required={f.required??true} maxLength={f.type==='number'?25:200}/>} {f.hint&&<small>{f.hint}</small>}</label>)}</>;}
export function OperationForm({operation,requestId,fields=[],hidden={},label='Salvar',children}:{operation:string;requestId:string;fields?:Field[];hidden?:Record<string,string>;label?:string;children?:React.ReactNode}){
 const [state,action,pending]=useActionState(operationAction,{message:''});
 return <form action={action} className="op-form"><input type="hidden" name="operation" value={operation}/><input type="hidden" name="request_id" value={state.requestId??requestId}/>{Object.entries(hidden).map(([k,v])=><input type="hidden" key={k} name={k} value={v}/>)}<div className="op-fields"><Fields fields={fields}/></div>{children}{state.message&&<p role="status" className="notice">{state.message}</p>}<button className="op-button" disabled={pending}>{pending?'Registrando…':label}</button></form>;
}
export function SaleForm({variants,channels,today,requestId}:{variants:Choice[];channels:Choice[];today:string;requestId:string}){
 const [items,setItems]=useState([{variant_id:'',quantity:'1',price:'',unit_cost:'0'}]);const [mode,setMode]=useState('stock');
 return <OperationForm operation="sale" requestId={requestId} label="Registrar venda" fields={[{name:'channel_id',label:'Canal de venda',type:'select',choices:channels},{name:'external_id',label:'Número do pedido'},{name:'date',label:'Data da venda',type:'date',value:today},{name:'due_date',label:'Previsão do recebimento',type:'date',value:today}]}>
 <label className="op-label">Como baixar o estoque<select name="stock_mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="stock">Usar produtos prontos</option><option value="produce">Produzir e vender agora</option><option value="historical">Venda antiga · custo informado, sem baixar estoque</option></select></label>
 <input type="hidden" name="items" value={JSON.stringify(items)}/>
 {items.map((item,index)=><div className="op-item" key={index}><label className="op-label">Produto / peça ou kit<select required value={item.variant_id} onChange={e=>setItems(items.map((it,i)=>i===index?{...it,variant_id:e.target.value,price:variants.find(v=>v.value===e.target.value)?.price??it.price}:it))}><option value="">Selecione</option>{variants.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select></label>{(['quantity','price',...(mode==='historical'?['unit_cost']:[])] as const).map(key=><label className="op-label" key={key}>{key==='quantity'?'Quantidade':key==='price'?'Preço unitário (R$)':'Custo histórico unitário (R$)'}<input required inputMode="decimal" value={item[key as keyof typeof item]} onChange={e=>setItems(items.map((it,i)=>i===index?{...it,[key]:e.target.value}:it))}/></label>)}{items.length>1&&<button type="button" className="op-link" onClick={()=>setItems(items.filter((_,i)=>i!==index))}>Remover item</button>}</div>)}
 {items.length<100&&<button type="button" className="op-secondary" onClick={()=>setItems([...items,{variant_id:'',quantity:'1',price:'',unit_cost:'0'}])}>Adicionar item</button>}
 <details><summary>Taxas, frete e descontos</summary><div className="op-fields"><Fields fields={[{name:'fees',label:'Taxas totais do pedido (R$)',required:false,hint:'Em branco usa as regras vigentes do canal. Zero significa venda sem taxas.'},...([['discount','Desconto'],['shipping_income','Frete pago pelo cliente'],['shipping','Frete pago pela empresa'],['taxes','Impostos'],['other','Outras despesas']] as const).map(([name,label])=>({name,label:label+' (R$)',type:'number' as const,value:'0'})),{name:'expected',label:'Valor esperado do repasse (R$)',required:false,hint:'Em branco: venda + frete do cliente − desconto − taxas − frete da empresa.'},{name:'notes',label:'Observações',type:'textarea',required:false}]}/></div></details>
 </OperationForm>;
}

