import Link from 'next/link';
import Decimal from 'decimal.js';
import {operationData} from '@/services/operations';
import {list,object,text as t,flag,choices,type Field,type Row} from '@/lib/operations';
import {formatMoney} from '@/lib/finance';
import {saoPauloToday,displayDate} from '@/lib/entries';
import {OperationForm,SaleForm} from '@/components/operation-form';
const money=(r:Row,k:string)=>formatMoney(t(r,k,'0'));
export function OpNav(){return <nav className="op-nav"><Link href="/dashboard">Visão geral</Link><Link href="/producao">Produção</Link><Link href="/estoque">Estoque</Link><Link href="/vendas">Vendas</Link><Link href="/recebiveis">Recebíveis</Link><Link href="/marketplaces">Canais e taxas</Link><Link href="/importacao">Importar</Link><Link href="/relatorios">Relatórios</Link></nav>;}
export function OpHeader({title,description}:{title:string;description:string}){return <><p className="eyebrow">BUENO EXPRESS</p><h1>{title}</h1><p className="intro">{description}</p><OpNav/></>;}
export function Filters({params,dates=true,channels=[],search=true}:{params:Record<string,string|undefined>;dates?:boolean;channels?:Row[];search?:boolean}){return <form className="op-filters">{search&&<label>Buscar<input name="q" defaultValue={params.q} placeholder="Nome, SKU ou pedido"/></label>}{dates&&<><label>De<input type="date" name="from" defaultValue={params.from??saoPauloToday().slice(0,7)+'-01'}/></label><label>Até<input type="date" name="to" defaultValue={params.to??saoPauloToday()}/></label></>}{channels.length>0&&<label>Canal<select name="channel_id" defaultValue={params.channel_id??''}><option value="">Todos</option>{channels.map(c=><option key={t(c,'id')} value={t(c,'id')}>{t(c,'name')}</option>)}</select></label>}<button className="op-secondary">Filtrar</button></form>;}
export function Pager({params,total,pageKey="page"}:{params:Record<string,string|undefined>;total:string;pageKey?:string}){const page=Math.max(1,Number(params[pageKey])||1);const href=(p:number)=>'?'+new URLSearchParams({...Object.fromEntries(Object.entries(params).filter((v):v is [string,string]=>!!v[1])),[pageKey]:String(p)});return <div className="op-pager"><span>Página {page} · {total} registros</span>{page>1&&<Link href={href(page-1)}>Anterior</Link>}{page*50<Number(total)&&<Link href={href(page+1)}>Próxima</Link>}</div>;}
export async function StockPage({params,view='stock'}:{params:Record<string,string|undefined>;view?:string}){
 const {data,canWrite}=await operationData(view==='costs'?'costs':'stock',params);const variants=list(data.variants),runs=list(data.runs),today=saoPauloToday();
 return <main className="content finance-content"><OpHeader title={view==='costs'?'Custos dos produtos':view==='production'?'Produção':'Estoque de produtos'} description="Da ficha de materiais ao produto pronto. Cada movimentação mantém o custo e o histórico."/><Filters params={params} dates={false}/>
 <section className="op-card"><h2>{view==='costs'?'Custo atual e capacidade':'Produtos prontos'}</h2>{!variants.length?<p className="op-empty">Cadastre um produto pela calculadora para começar.</p>:<div className="op-table"><table><thead><tr><th>Produto / SKU</th><th>Prontos</th><th>Custo em estoque</th><th>Custo atual da ficha</th><th>Pode produzir</th><th>Ações</th></tr></thead><tbody>{variants.map(v=>{const recipe=object(v.recipe);return <tr key={t(v,'id')}><td><strong>{t(v,'product_name')}</strong><small>{t(v,'name')} · {t(v,'sku')}</small></td><td>{new Decimal(t(v,'stock_quantity','0')).toFixed()}</td><td>{money(v,'stock_value')}</td><td>{recipe.error?<span>{t(recipe,'error')}</span>:money(recipe,'unit_cost')}</td><td>{t(recipe,'capacity')||'Sem materiais vinculados'}</td><td><Link href={'/produtos?product='+t(v,'product_id')+'&variant='+t(v,'id')}>Ficha</Link><br/><Link href={'/calculadoras?mode='+((object(v.production).filament_id||object(object(v.attributes).calculator).mode==="3d")?'3d':'ml')+'&product='+t(v,'product_id')+'&variant='+t(v,'id')}>Ajustar custo</Link></td></tr>})}</tbody></table></div>}<Pager params={params} total={t(data,'total','0')}/></section>
 {canWrite&&view!=='costs'&&<section className="op-card"><h2>Registrar produção ou movimentação</h2><OperationForm requestId={crypto.randomUUID()} operation="produce" label="Registrar movimentação" fields={[{name:'variant_id',label:'Produto',type:'select',choices:variants.filter(v=>flag(v,'active')).map(v=>({value:t(v,'id'),label:t(v,'product_name')+' · '+t(v,'sku')}))},{name:'kind',label:'Tipo',type:'select',value:'production',choices:[{value:'production',label:'Produção · consumir insumos da ficha'},{value:'opening',label:'Entrada de produtos já prontos'},{value:'loss',label:'Perda de produtos prontos'}]},{name:'quantity',label:'Quantidade de peças / kits',type:'number'},{name:'date',label:'Data',type:'date',value:today},{name:'unit_cost',label:'Custo unitário da entrada pronta (R$)',type:'number',value:'0',hint:'Usado somente para produtos já prontos. Produção usa a ficha; perda usa o custo do estoque.'},{name:'reason',label:'Motivo ou observação',value:'Produção do dia'}]}/><p className="op-help">A produção baixa todos os materiais da ficha, inclusive embalagens. A venda do produto pronto não consome esses materiais novamente. Busque o SKU acima para selecionar produtos fora desta página.</p></section>}
 <section className="op-card"><h2>Histórico de produção e ajustes</h2>{!runs.length?<p className="op-empty">Nenhuma produção registrada.</p>:runs.map(r=><details key={t(r,'id')} className="op-record"><summary>{displayDate(t(r,'date'))} · {t(r,'product_name')} · {t(r,'quantity')} un. · {t(r,'status')==='reversed'?'Estornado':({production:'Produção',opening:'Entrada pronta',loss:'Perda'}[t(r,'kind')]??t(r,'kind'))}</summary><p>Custo unitário registrado: {money(r,'unit_cost')} · {t(r,'reason')}</p>{list(object(r.snapshot).parts).map(p=><p key={t(p,'id')}>{t(p,'name')}: {t(p,'quantity')} {t(p,'unit')} por unidade · {money(p,'cost')}/{t(p,'unit')}</p>)}{canWrite&&t(r,'status')==='posted'&&<OperationForm operation="reverse_production" requestId={crypto.randomUUID()} hidden={{id:t(r,'id')}} label="Estornar movimentação" fields={[{name:'date',label:'Data do estorno',type:'date',value:today},{name:'reason',label:'Motivo do estorno'}]}/>}</details>)}<Pager params={params} total={t(data,"run_total","0")} pageKey="history_page"/></section></main>;
}
export async function SalesPage({params,receivables=false}:{params:Record<string,string|undefined>;receivables?:boolean}){
 const {data,canWrite}=await operationData(receivables?'receivables':'sales',params);const channels=list(data.channels),orders=list(data.orders),today=saoPauloToday();
 const paymentFields:Field[]=[{name:'date',label:'Data',type:'date',value:today},{name:'amount',label:'Valor (R$)',type:'number'},{name:'account_id',label:'Conta financeira',type:'select',choices:choices(list(data.accounts))},{name:'category_id',label:'Categoria',type:'select',choices:choices(list(data.categories))},{name:'reason',label:'Observação',value:'Repasse do pedido'}];
 return <main className="content finance-content"><OpHeader title={receivables?'Recebíveis e conciliação':'Vendas'} description={receivables?'Compare o repasse previsto com o recebido. A baixa entra no financeiro sem duplicar o faturamento.':'Registre pedidos, custos e lucro. Cada venda guarda os valores daquele momento.'}/><Filters params={params} dates={!receivables} channels={channels}/>
 {!receivables&&canWrite&&<details className="op-card" open={!orders.length}><summary>Registrar venda</summary>{!channels.some(c=>flag(c,'active'))?<p className="op-empty">Primeiro <Link href="/marketplaces">cadastre um canal de venda</Link>.</p>:<SaleForm variants={list(data.variants).map(v=>({value:t(v,'id'),label:t(v,'name')+' · '+t(v,'sku'),price:t(v,'price')}))} channels={choices(channels.filter(c=>flag(c,'active')))} today={today} requestId={crypto.randomUUID()}/>}</details>}
 <section className="op-card"><h2>{receivables?'Repasses dos pedidos':'Pedidos registrados'}</h2>{!orders.length?<p className="op-empty">Nenhum pedido neste período. Você pode cadastrar ou importar suas vendas quando quiser.</p>:orders.map(o=><details key={t(o,'id')} className="op-record" open={params.id===t(o,'id')}><summary><strong>{t(o,'external_id')}</strong> · {t(o,'channel_name')} · {displayDate(t(o,'date'))} · {money(o,'gross')} <span className="badge">{t(o,'payment_status')}</span></summary><div className="op-metrics"><article><small>Receita líquida da venda</small><strong>{money(o,'net')}</strong></article><article><small>Custo dos produtos</small><strong>{money(o,'cost')}</strong></article><article><small>Lucro do pedido</small><strong>{money(o,'profit')}</strong></article><article><small>Previsto / recebido</small><strong>{money(o,'expected')} / {money(o,'received')}</strong></article></div><p>Vencimento: {displayDate(t(o,'due_date'))} · Taxas: {money(o,'fees')} · Impostos: {money(o,'taxes')} · Frete: {money(o,'shipping')}</p>{t(o,'stock_mode')==='historical'&&<p className="notice">Venda histórica com custo informado. Não altera estoque.</p>}<div className="op-table"><table><thead><tr><th>Item</th><th>Qtd.</th><th>Venda unitária</th><th>Custo registrado</th></tr></thead><tbody>{list(o.items).map(i=><tr key={t(i,'id')}><td>{t(i,'name')} · {t(i,'sku')}</td><td>{t(i,'quantity')}</td><td>{money(i,'price')}</td><td>{money(i,'unit_cost')}</td></tr>)}</tbody></table></div>{t(o,'notes')&&<p>{t(o,'notes')}</p>}
 {list(o.receipts).map(r=><p key={t(r,'id')}>{displayDate(t(r,'date'))} · {new Decimal(t(r,'amount','0')).isNegative()?'Devolução':'Recebimento'}: {money(r,'amount')} · {t(r,'reason')}</p>)}
 {canWrite&&t(o,'status')==='posted'&&<div className="op-actions"><details><summary>Registrar recebimento</summary><OperationForm operation="receive" requestId={crypto.randomUUID()} hidden={{id:t(o,'id')}} fields={paymentFields.map(f=>f.name==='category_id'?{...f,choices:choices(list(data.categories).filter(c=>['receita','ambos'].includes(t(c,'type'))))}:f)} label="Registrar recebimento"/></details><details><summary>Conciliar / encerrar repasse</summary><OperationForm operation="close_receivable" requestId={crypto.randomUUID()} hidden={{id:t(o,'id')}} fields={[{name:'closed',label:'Situação',type:'select',value:'true',choices:[{value:'true',label:'Encerrar · preservar eventual diferença'},{value:'false',label:'Reabrir cobrança'}]},{name:'reason',label:'Motivo / diferença identificada'}]} label="Salvar conciliação"/></details><details><summary>Devolução ou cancelamento</summary>{new Decimal(t(o,'received','0')).gt(0)?<OperationForm operation="refund" requestId={crypto.randomUUID()} hidden={{id:t(o,'id')}} fields={paymentFields.map(f=>f.name==='category_id'?{...f,choices:choices(list(data.categories).filter(c=>['despesa','ambos'].includes(t(c,'type'))))}:f)} label="Registrar devolução financeira"/>:<OperationForm operation="cancel_sale" requestId={crypto.randomUUID()} hidden={{id:t(o,'id')}} fields={[{name:'date',label:'Data',type:'date',value:today},{name:'reason',label:'Motivo'}]} label="Cancelar e devolver produtos ao estoque"/>}</details></div>}</details>)}<Pager params={params} total={t(data,'total','0')}/></section></main>;
}
export async function ChannelsPage({params}:{params:Record<string,string|undefined>}){
 const {data,canWrite}=await operationData('settings',params);const channels=list(data.channels),rules=list(data.rules);return <main className="content finance-content"><OpHeader title="Canais e taxas" description="Cadastre onde vende e as taxas da sua operação. Regras com vigência e faixa de valor são somadas por pedido."/><div className="op-columns"><section className="op-card"><h2>Canais de venda</h2>{channels.map(c=><details key={t(c,'id')} className="op-record"><summary>{t(c,'name')} · {flag(c,'active')?'Ativo':'Arquivado'}</summary>{canWrite&&<OperationForm operation="channel" requestId={crypto.randomUUID()} hidden={{id:t(c,'id')}} fields={[{name:'name',label:'Nome',value:t(c,'name')},{name:'active',label:'Situação',type:'select',value:String(flag(c,'active')),choices:[{value:'true',label:'Ativo'},{value:'false',label:'Arquivado'}]}]}/>}</details>)}{canWrite&&<OperationForm operation="channel" requestId={crypto.randomUUID()} fields={[{name:'name',label:'Novo canal (ex.: Mercado Livre)'}]} label="Cadastrar canal"/>}</section><section className="op-card"><h2>Nova regra de taxa</h2>{canWrite&&<OperationForm operation="fee" requestId={crypto.randomUUID()} fields={[{name:'channel_id',label:'Canal',type:'select',choices:choices(channels)},{name:'name',label:'Nome da regra'},{name:'percentage',label:'Percentual sobre o total dos itens (%)',type:'number',value:'0'},{name:'fixed',label:'Taxa fixa por pedido (R$)',type:'number',value:'0'},{name:'minimum',label:'Valor mínimo do pedido (R$)',type:'number',value:'0'},{name:'maximum',label:'Valor máximo (R$)',required:false},{name:'starts',label:'Válida desde',type:'date',value:saoPauloToday()},{name:'ends',label:'Válida até (opcional)',type:'date',required:false}]} label="Salvar regra"/>}</section></div><section className="op-card"><h2>Regras ativas</h2>{rules.length?rules.map(r=><div className="op-record" key={t(r,'id')}><p><strong>{t(r,'name')}</strong> · {t(channels.find(c=>c.id===r.channel_id)??{},'name')} · {t(r,'percentage')}% + {money(r,'fixed')} · desde {displayDate(t(r,'starts'))}</p>{canWrite&&<OperationForm operation="fee" requestId={crypto.randomUUID()} hidden={{id:t(r,'id'),channel_id:t(r,'channel_id')}} label="Desativar regra"/>}</div>):<p className="op-empty">Sem regras. Taxas podem ser informadas diretamente em cada venda.</p>}</section></main>;
}


