import Link from 'next/link';
import Decimal from 'decimal.js';
import {operationData} from '@/services/operations';
import {list,object,text as t,type Row} from '@/lib/operations';
import {formatMoney} from '@/lib/finance';
import {saoPauloToday,displayDate} from '@/lib/entries';
import {OperationForm} from './operation-form';
import {Filters,OpHeader} from './operations-pages';
function money(r:Row,k:string){return formatMoney(t(r,k,'0'));}
function DataTable({rows,columns}:{rows:Row[];columns:[string,string,boolean][]}){return rows.length?<div className="op-table"><table><thead><tr>{columns.map(([k,label])=><th key={k}>{label}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{columns.map(([k,,currency])=><td key={k}>{currency?money(r,k):t(r,k,'—')}</td>)}</tr>)}</tbody></table></div>:<p className="op-empty">Sem registros no período.</p>;}
export async function ReportPage({params,view='dashboard'}:{params:Record<string,string|undefined>;view?:string}){
 const {data,canWrite}=await operationData(view,params);const metrics=object(data.metrics),cash=object(data.cash),daily=list(data.daily),channels=list(data.by_channel),products=list(data.by_product),goals=list(data.goals),alerts=list(data.alerts);const titles:Record<string,string>={dashboard:'Sua operação em uma visão',reports:'Relatórios',analysis:'Análise da operação'};
 const highest=daily.reduce((max,r)=>Decimal.max(max,new Decimal(t(r,'gross','0')).abs(),new Decimal(t(r,'profit','0')).abs()),new Decimal(1));
 const exportQuery=new URLSearchParams({from:t(data,'from'),to:t(data,'to'),...(params.channel_id?{channel_id:params.channel_id}:{})});
 return <main className="content finance-content"><OpHeader title={titles[view]} description="Vendas, custos e recebimentos conectados. Os resultados usam os valores registrados, com o histórico preservado."/><Filters params={params} channels={list(data.channels)} search={false}/><p className="op-help">Competência: {displayDate(t(data,'from'))} a {displayDate(t(data,'to'))}. Caixa segue as datas dos recebimentos. Atualizado nesta consulta.</p>
 <div className="op-metrics">{([['gross','Faturamento dos itens'],['net','Receita líquida das vendas'],['profit','Lucro dos pedidos'],['expenses','Despesas operacionais'],['operating_profit','Resultado após despesas'],['cost','Custo dos produtos vendidos'],['fees','Taxas'],['receivable','Repasses em aberto']] as const).map(([key,label])=><article key={key}><small>{label}</small><strong>{money(metrics,key)}</strong></article>)}<article><small>Pedidos / unidades</small><strong>{t(metrics,'orders','0')} / {t(metrics,'units','0')}</strong></article><article><small>Margem dos pedidos</small><strong>{t(metrics,'margin','—')}%</strong></article><article><small>Ticket médio</small><strong>{money(metrics,'ticket')}</strong></article><article><small>Saldo financeiro atual</small><strong>{money(cash,'balance')}</strong></article><article><small>Contas a pagar</small><strong>{money(cash,'payable')}</strong></article><article><small>Recebido no mês atual</small><strong>{money(cash,'received')}</strong></article><article><small>Pago no mês atual</small><strong>{money(cash,'paid')}</strong></article></div>
 <p className="op-help">Compras de insumos vinculadas não são descontadas novamente do resultado: seu custo entra quando o produto é vendido. Despesas manuais devem conter apenas gastos ainda não incluídos no custo do produto. O filtro de canal afeta vendas; despesas e saldo financeiro são da empresa.</p>
 {view==='analysis'&&<section className="op-card"><h2>Diagnóstico com os dados registrados</h2>{new Decimal(t(metrics,'orders','0')).isZero()?<p>Ainda não há vendas no período. Cadastre seus insumos, simule os produtos e registre as primeiras produções e vendas para gerar a análise.</p>:<><p>Você faturou <strong>{money(metrics,'gross')}</strong> em {t(metrics,'orders')} pedidos. O lucro desses pedidos foi <strong>{money(metrics,'profit')}</strong>, antes das despesas gerais.</p><p>{new Decimal(t(metrics,'operating_profit','0')).lt(0)?'As despesas superaram o resultado das vendas. Revise os produtos de menor margem e os maiores gastos abaixo.':'O resultado após as despesas registradas está positivo ou equilibrado.'}</p>{channels[0]&&<p>Maior lucro entre canais: <strong>{t(channels[0],'name')}</strong> ({money(channels[0],'profit')}).</p>}{products.filter(p=>new Decimal(t(p,'profit','0')).lt(0)).map(p=><p key={t(p,'sku')}>Revisar preço/custo de <Link href={'/produtos?q='+encodeURIComponent(t(p,'sku'))}>{t(p,'name')}</Link>: resultado {money(p,'profit')}.</p>)}<p>Há {money(metrics,'receivable')} em repasses abertos. Receber esses valores melhora o caixa, sem criar novo faturamento.</p></>}<p className="op-help">Análise automática por regras sobre os registros deste período. Não faz previsões nem altera seus dados.</p></section>}
 <div className="op-columns"><section className="op-card"><h2>Faturamento e lucro por dia</h2>{daily.length?<div className="op-chart">{daily.map(r=><div className="op-chart-row" key={t(r,'date')}><span>{displayDate(t(r,'date')).slice(0,5)}</span><div><div className="op-bar" style={{width:new Decimal(t(r,'gross','0')).div(highest).mul(100).toNumber()+'%'}}/><div className="op-bar profit" style={{width:new Decimal(t(r,'profit','0')).abs().div(highest).mul(100).toNumber()+'%',background:new Decimal(t(r,'profit','0')).lt(0)?'#dc2626':undefined}}/></div><small>{money(r,'gross')} / {money(r,'profit')}</small></div>)}</div>:<p className="op-empty">O gráfico aparece após as primeiras vendas.</p>}<p className="op-help">Cinza: faturamento · verde: lucro · vermelho: prejuízo</p></section><section className="op-card"><h2>Atenção na operação</h2>{alerts.length?alerts.slice(0,50).map(a=><div className="op-record" key={t(a,'key')}><Link href={t(a,'href')}>{t(a,'message')}</Link>{canWrite&&<OperationForm operation="resolve" requestId={crypto.randomUUID()} hidden={{key:t(a,'key')}} label="Marcar como visto"/>}</div>):<p className="op-empty">Nenhum alerta encontrado nos registros atuais.</p>}</section></div>
 <section className="op-card"><h2>Resultado por canal</h2><DataTable rows={channels} columns={[["name","Canal",false],["orders","Pedidos",false],["gross","Faturamento",true],["profit","Lucro dos pedidos",true]]}/></section><section className="op-card"><h2>Resultado por produto</h2><DataTable rows={products} columns={[["sku","SKU",false],["name","Produto",false],["units","Unidades",false],["gross","Venda",true],["cost","Custo histórico",true],["profit","Lucro alocado",true]]}/><p className="op-help">Despesas do pedido são distribuídas proporcionalmente ao valor dos itens. Até 100 produtos exibidos.</p></section>
 <section className="op-card"><h2>Despesas por categoria</h2><DataTable rows={list(data.expense_categories)} columns={[["name","Categoria",false],["amount","Total",true]]}/></section>
 <section className="op-card"><h2>Metas da empresa</h2>{goals.map(g=><div className="op-record" key={t(g,'id')}><p><strong>{{gross:'Faturamento',profit:'Lucro dos pedidos',orders:'Pedidos',margin:'Margem'}[t(g,'metric')]}</strong> · {displayDate(t(g,'starts'))} a {displayDate(t(g,'ends'))}</p><p>{t(g,'actual')} de {t(g,'target')} · {t(g,'progress')}%</p><progress max="100" value={Math.min(100,Math.max(0,Number(t(g,'progress','0'))))}/>{canWrite&&<OperationForm operation="goal" requestId={crypto.randomUUID()} hidden={{id:t(g,'id')}} label="Arquivar meta"/>}</div>)}{canWrite&&<details><summary>Adicionar meta</summary><OperationForm operation="goal" requestId={crypto.randomUUID()} fields={[{name:'metric',label:'Indicador',type:'select',value:'gross',choices:[{value:'gross',label:'Faturamento (R$)'},{value:'profit',label:'Lucro dos pedidos (R$)'},{value:'orders',label:'Quantidade de pedidos'},{value:'margin',label:'Margem dos pedidos (%)'}]},{name:'target',label:'Objetivo',type:'number'},{name:'starts',label:'Início',type:'date',value:saoPauloToday().slice(0,7)+'-01'},{name:'ends',label:'Fim',type:'date',value:saoPauloToday()}]}/></details>}</section>
 <section className="op-card"><h2>Exportar dados</h2><div className="op-nav">{[['daily','Por dia'],['by_channel','Por canal'],['by_product','Por produto'],['expense_categories','Despesas']].map(([kind,label])=><a key={kind} href={'/relatorios/exportar?'+exportQuery+'&kind='+kind}>{label} · CSV</a>)}</div><p className="op-help">CSV compatível com Excel. Os filtros desta consulta acompanham a exportação.</p></section>
 </main>;
}

